### ISSUE TITLE
How to convert `fl::Variable` to `fl::Tensor`

### ISSUE THREAD

**Issue by mmbejani** [flashlight/flashlight#1001]
### Question
Assume we have a variable `fl::Variable` and a variable `fl::Tensor`. How can I covert one to another?

**Comment by jacobkahn** [comment]
`fl::Variable::tensor()` (the `.tensor()` method on Variable) and `Variable(Tensor tensor)` (the Variable constructor).

[Docs](https://fl.readthedocs.io/en/latest/variable.html).
