### ISSUE TITLE
Is the ctc decoder supports word piece decoding ?

### ISSUE THREAD

**Issue by Slyne** [flashlight/flashlight#1031]
### Question
I've found this [tutorial](https://pytorch.org/audio/main/tutorials/asr_inference_with_ctc_decoder_tutorial.html#beam-search-decoder) from pytorch.  It mentions the decoder is ported from flashlight. However, it doesn't mention whether this decoder support wordpiece/sentpiece/bpe decoding.  I've tried several audio files and with a model whose outputs are bpe, but the output is just empty. Not sure if there's any guide on how to do this.

**Comment by jacobkahn** [comment]
@Slyne — would you mind moving your question to https://github.com/flashlight/text? We've moved decoding utilities there.

In short — yes, the decoder supports word piece/sentencepiece/BPE decoding. The decoder doesn't care about the modeling unit -- if you provide a token set that's composed of word pieces and a lexicon that has word spellings in terms of word pieces, then you can do beam search in the same way as you'd do with individual letters, but using word pieces instead.
