### ISSUE TITLE
Flashlight 0.3v is not generating all the needed ASR library files like the previous version. 

### ISSUE THREAD

**Issue by vchagari** [flashlight/flashlight#1046]
### Bug Description
Flashlight version 0.3v is not generating all the ASR related Libraries like the previous version. 

Libraries that didn't get generated by V0.3:
1. flashlight-app-asr
2. flashlight-app-imgclass
3. flashlight-app-lm
4. fl-libraries

#### Reproduction Steps
Flashlight Compilation Steps: 

V0.3 Flashlight with latest Commit: 
    git clone https://github.com/facebookresearch/flashlight.git
    cd flashlight
    mkdir flashlight_install
    git checkout e16682fa32df30cbf675c8fe010f929c61e3b833
    mkdir build
    cd build
    cmake .. -DCMAKE_BUILD_TYPE=Release -DFL_BACKEND=CUDA -DFL_USE_ONEDNN=OFF -DFL_BUILD_APP_ASR=ON -DFL_BUILD_APP_ASR_TOOLS=ON -DFL_BUILD_PKG_RUNTIME=ON -DFL_BUILD_LIB_SEQUENCE=ON -DFL_BUILD_LIB_TEXT=ON -DFL_BUILD_LIB_AUDIO=ON -DFL_BUILD_LIB_COMMON=ON -DFL_BUILD_PKG_SPEECH=ON -DFL_BUILD_LIB_SET=ON -DCMAKE_INSTALL_PREFIX=/flashlight/flashlight_install/
    make install -j$(nproc)

**********
Previous Version: 
Flashlight Compilation Steps for previous/older version:
git clone https://github.com/facebookresearch/flashlight.git
cd flashlight
mkdir flashlight_install
git checkout 1061e1727c77fac644713047be4c2fb95c02fd55
mkdir build 
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DFL_BACKEND=CUDA -DFL_BUILD_APP_ASR=ON -DFL_BUILD_APP_ASR_TOOLS=ON -DCMAKE_INSTALL_PREFIX=/flashlight/flashlight_install/
    make install -j$(nproc)

### Platform and Hardware
[Please list your operating system, [GPU] hardware, compiler, and other details if relevant]
Ubuntu OS 18.04 LTS
Nvidia GPU,
GCC

#### Additional Context
V0.3 Generated the following libraires: 
libfl_lib_set.a
libfl_lib_common.a
libfl_lib_audio.a
libfl_lib_sequence.a
libkenlm_util.a
libflashlight.a
libkenlm.a
libfl_pkg_runtime.a
libfl_lib_text.a
libfl_pkg_speech.a

Previous Version on commit: 1061e1727c77fac644713047be4c2fb95c02fd55
libkenlm_util.a
libkenlm.a
libfl-libraries.a
libflashlight.a
libflashlight-app-imgclass.a
libflashlight-app-lm.a
libflashlight-app-asr.a

**Comment by jacobkahn** [comment]
@vchagari — the name of the libraries has changed (and may change again in the future before the next release).

`libfl_pkg_speech` now contains the ASR library. The binaries in question (i.e. `fl_asr_train`) depend on `libfl_pkg_speech` and `libflashlight`.

We're making changes to Flashlight components still, and it may be some time before things stabilize. Hope this helps clarify — let us know if you have further questions.

**Comment by VamsiChagari** [comment]
Thank you for the info @jacobkahn. 
Looks like the API interfaces are also changed in the 3.0 version when compared to the previous version. I am unable to compile the inference code I have with the new version (3.0) Libraries.

**Comment by vchagari** [comment]
Thank you for the Info @jacobkahn. 

Looks like the API's have changed in the Flashlight 0.3 Version. I am unable to compile/use the existing inference code after updating the flashlight to v0.3 along with the generated libraries.

**Comment by jacobkahn** [comment]
@vchagari — the APIs have indeed changed — we have not yet updated the inference pipeline and other downstream dependencies to work with Flashlight >= 0.3, but we'll hopefully make those changes in the coming months.
