### ISSUE TITLE
ONNX Support?

### ISSUE THREAD

**Issue by charlesrwest** [flashlight/flashlight#1048]
Hello!

Really excited to see a C++ first machine learning library.  I've been working in C++ since 2007 and literally only picked up python because there weren't good options for machine learning in C++.  

That said, I can't port over my existing setup without being able to export to ONNX so that it can run on TensorRT for edge deployment.  If I may ask, is ONNX support on the horizon or pretty far off?

Thanks!

**Comment by jacobkahn** [comment]
@charlesrwest — ONNX support isn't currently something we'll have the resources for for the foreseeable future; but do say so if you're interested in contributing!
