### ISSUE TITLE
Is there any way to "automatically" not record an autograd graph during a block of code?

### ISSUE THREAD

**Issue by alexjwilliams** [flashlight/flashlight#1073]
As far as I can tell, the answer is no.  I am interested in such a feature to reduce memory usage in sections of code where I don't need gradients.

The return statement of a typical function in `fl/autograd/Functions.cpp` looks something like `return Variable(output, {input}, gradFunc);`. This means that, by default, an autograd function's input and gradFunc are stored in its output. We can call `setCalcGrad(false)` on an existing `Variable` to clear its `inputs` and its `gradFunc`. 

Suppose we wanted to disable the recording of `inputs` and `gradFunc`s in all intermediate `Variable`s created during a call to a `Module`'s `forward()` method. To do this, we could modify the code of `forward()` so that we call `setCalcGrad(false)` on the outputs of every operator/function from `fl/autograd/Functions.cpp`. Is there any way to achieve a similar result without touching `forward()`'s code?

**Comment by jacobkahn** [comment]
@alexjwilliams — you can use `module.train()` (which will effectively call `setCalcGrad(false)` recursively for each of the module's parameters) and ensure that input `Variable`s passed to the module don't have gradient recording on. Hope this helps.
