### ISSUE TITLE
building/installing Python bindings page is not found

### ISSUE THREAD

**Issue by mydigitalpro9** [flashlight/flashlight#1074]
### Bug Description
The link given to install binding on documentation is giving 404 page

#### Reproduction Steps
- Open https://github.com/flashlight/flashlight
- Search for Instructions for building/installing Python bindings in Readme page
- Click on link next to "building/installing Python bindings"
- it will redirect to 404 page.

### Platform and Hardware
Chrome browser or any other browser

#### Additional Context
Please refer  screenshot for 404 error page

<img width="1289" alt="Screenshot 2023-01-26 at 3 41 17 PM" src="https://user-images.githubusercontent.com/105585779/214813019-d420e8bc-a268-466b-8a5f-c4988a8cc8b2.png">

**Comment by jacobkahn** [comment]
@mydigitalpro9 — bindings now exist here https://github.com/flashlight/text. What directed you here?

**Comment by jason-kane** [comment]
I ran into likely the same; it's in https://github.com/flashlight/flashlight/blob/main/README.md#requirements

**Comment by jacobkahn** [comment]
Fixed in https://github.com/flashlight/flashlight/pull/1097
