### ISSUE TITLE
Support Windows build  / Static build success with some adaptations

### ISSUE THREAD

**Issue by MaxCoo** [flashlight/flashlight#1078]
### Feature Description
The lack of Windows support is sad because I have build the debug/release `flashlight.lib` on my computer. Sorry if the information provided are raw but this is a first attempt. I''ve just download the latest ArrayFire prebuilt distribution and compiled the project for GPU, so with the `afcuda.dll`. ArrayFire is detected by cmake without problem.

#### Use Case
1. Because NVIDIA NCCL is not available on Windows OS, in a first step I just desactivate the `FL_BUILD_DISTRIBUED` option. I don't know if I can use GLOO instead NCCL because when `FL_BUILD_DISTRIBUED` is ON, the NCCL library path are mandatory.
2. Because FLASHLIGHT use a compiler that support dynamic symbol export (`-rdynamic` flag), I just use the [dlfcn-win32](https://github.com/dlfcn-win32/dlfcn-win32) project instead that fullfill the required functions when `dlfcn.h` is included. 
3. About code adaptation, I add the missing M_PI (Posix) when needed.
4. Another problem on Windows comes with the Flashlight's cereal macro `FL_SAVE_LOAD_WITH_BASE`. Visual Studio do not manage correctly the "without parameters" case, so when only a Base Class name (one argument) is passed to `FL_SAVE_LOAD_WITH_BASE`, the empty args generate a comma just before the parenthesis. So the easy trick is the copy the `FL_SAVE_LOAD_WITH_BASE` and rename the macro `FL_SAVE_LOAD_WITH_BASE_WITH_ARGS` and remove the ARGS (second parameter) in the `FL_SAVE_LOAD_WITH_BASE`. Maybe there's a cleanest way to correct this problem, but this one work.
5. There's some code that are C++20 (ex. std::iota in `flashlight\fl\dataset\ShuffleDataset.cpp`) where the project is set to C++17 and do not compile with C++20 on Visual Studio. Maybe Linux compiler are more relax about the standard. So for this case I've just put a default implementation renamed `std_iota`.

This is almost the changes needed to allow to build the flashlight libraries (exported as static library but with DLL runtime `MD`).

```
Debug : flashlight.lib (517 594 Kb)
Release : flashlight.lib (75 973 Kb)
```

Most of the Test project do not build because there's some other specifics errors to investigate. But some are build and run fine (I think).

```
AdaptiveClassification.exe
Benchmark.exe
Classification.exe
LinearRegression.exe
Mnist.exe
Perceptron.exe
RnnClassification.exe
RnnLm.exe
Xor.exe
```

I hope that can help some users who want to use Flashlight on Windows. Maybe a first step for a official Windows support !!!

In any case, thank's a lot for this project !!!

#### Additional Context
OS: Windows 11 22H2 (22621.1265)
IDE: Visual Studio 20222 64 bits (17.4.5)
Processor : 13th Gen Intel(R) Core(TM) i9-13900K   3.00 GHz
GPU : NVIDIA GeForce RTX 4080 16 GB / CUDA : 12.0
RAM : 64 GB

**Comment by jacobkahn** [comment]
@MaxCoo — thanks for all of this info! If you have PRs you'd like to send to fix some of these things, they'd be welcome.

I'm in the process of rewriting Flashlight's CI to include building and testing on Windows with MSVC, so that should give us a better signal. That work is happening in https://github.com/flashlight/flashlight/pull/1082.

**Comment by jacobkahn** [comment]
@MaxCoo — building on Windows with MSVC is now supported, and there are CI baselines as well with Windows on CPU and GPU. Windows functionality remains relatively untested - do pilot this and open an issue on GH if you run into problems!
