### ISSUE TITLE
find_package(cereal) fails to find cereal

### ISSUE THREAD

**Issue by yurivict** [flashlight/flashlight#1086]
### Bug Description
When ```find_package(cereal)``` is after the line ```set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")``` - it fails to find cereal. It appears that ```Findcereal.cmake``` causes this failure. It looks like ```Findcereal.cmake``` isn't needed since cereal provides its own cmake scripts.

#### Reproduction Steps
Regular configure.

### Platform and Hardware
FreeBSD 13.1

cereal-1.3.2

**Comment by jacobkahn** [comment]
@yurivict — this was here to support legacy configurations, but removing it makes sense now. I'll do so soon.

**Comment by jacobkahn** [comment]
@yurivict `Findcereal.cmake` isn't in `main` — it was removed in https://github.com/flashlight/flashlight/pull/1060 favor of the config-based approach. If you're checked out to an old version, you should use old dependencies as loosely specified by CMake. If not, I'd recommend sticking to `main`.
