### ISSUE TITLE
terminate called after throwing an instance of 'std::invalid_argument'

### ISSUE THREAD

**Issue by zoldaten** [flashlight/flashlight#1123]
### Bug Description
when i try example on raspberry pi aarch64 i got error:

```
~/flashlight/build/flashlight/fl/examples $ ./Mnist mnist_dataset
terminate called after throwing an instance of 'std::invalid_argument'
  what():  TensorExtensionRegistrar::getTensorExtensionCreationFunc: no tensor extensions registered for given backend.
Aborted
```

### Platform and Hardware
```
Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
```

#### Additional Context
my mnist dir looks like:
`t10k-images-idx3-ubyte  t10k-labels-idx1-ubyte  train-images-idx3-ubyte  train-labels-idx1-ubyte`

flashlight i built as follows:
`cmake ..       -DFL_BUILD_ARRAYFIRE=ON 	  -DFL_BUILD_LIBRARIES=OFF 	  -DFL_BUILD_APPS=OFF       -DFL_USE_ONEDNN=OFF       -DFL_BUILD_TESTS=OFF       -DFL_BUILD_EXAMPLES=ON       -DFL_BUILD_SCRIPTS=OFF 	  -DCMAKE_BUILD_TYPE=Release`

**Comment by jacobkahn** [comment]
@zoldaten — you'll need an autograd backend to run the examples fully; on CPU, this is a work in progress, but you can install oneDNN 2.x for now.
