### ISSUE TITLE
Google Colab Fails to Launch

### ISSUE THREAD

**Issue by Jibril2** [flashlight/flashlight#1138]
### Bug Description
Google Colab Instance ( https://colab.research.google.com/github/flashlight/flashlight/blob/main/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb#scrollTo=KZs5ucthy38A ) fails on Cell 2

#### Reproduction Steps
Run Cell 1, it succeeds.
Run Cell 2, it fails due to No CMAKE_CUDA_COMPILER found.

### Platform and Hardware
Google Colab Pro

**Comment by jacobkahn** [comment]
@Jibril2 -- the demo requires a Colab instance with GPU support that has CUDA installed.
