### ISSUE TITLE
NameError: name 'CriterionType' is not defined

### ISSUE THREAD

**Issue by mukherjeesougata** [flashlight/flashlight#1168]
I am trying to decode a fine-tuned ASR model,fine-tuned using the [vakyansh](https://github.com/Open-Speech-EkStep/vakyansh-wav2vec2-experimentation) toolkit using the [this](https://github.com/Open-Speech-EkStep/vakyansh-wav2vec2-experimentation/blob/main/utils/inference/infer.py) script and the following command line:-
```
python ../../utils/inference/infer.py ${data_path} --task audio_pretraining \
  --nbest 1 --path ${checkpoint_path} --gen-subset ${subset} --results-path ${result_path} --w2l-decoder viterbi \
  --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 6000000 \
  --post-process letter --model-overrides "{'w2v_path':'${pretrained_model_path}'}"
```
But it is showing the following error:-
```
Traceback (most recent call last):
  File "../../utils/inference/infer.py", line 428, in <module>
    cli_main()
  File "../../utils/inference/infer.py", line 424, in cli_main
    main(args)
  File "../../utils/inference/infer.py", line 283, in main
    generator = build_generator(args)
  File "../../utils/inference/infer.py", line 268, in build_generator
    return W2lViterbiDecoder(args, task.target_dictionary)
  File "/data/Sougata/vakyansh_latest/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/examples/speech_recognition/w2l_decoder.py", line 115, in __init__
    super().__init__(args, tgt_dict)
  File "/data/Sougata/vakyansh_latest/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/examples/speech_recognition/w2l_decoder.py", line 56, in __init__
    self.criterion_type = CriterionType.CTC
NameError: name 'CriterionType' is not defined
```
Flashlight-text was installed using [these](https://github.com/flashlight/text/blob/main/bindings/python/README.md#build-instructions) set of commands and Flashlight-sequence using [these](https://github.com/flashlight/text/blob/main/bindings/python/README.md#build-instructions) set of commands.
I have also tried installing flashlight-text and flashlight-sequence using the command ```python -m pip install flashlight-text flashlight-sequence```, but still it is giving the same error.
I have run ```from flashlight.lib.text.decoder import CriterionType```, it is working.

**Comment by Lalaramarya** [comment]
@tlikhomanenko, I am also facing the same problem. Can you please suggest a solution to this?

**Comment by mukherjeesougata** [comment]
I am still facing this issue. @jacobkahn Can you Kindly, please suggest a solution to this?

**Comment by asadullah797** [comment]
I am also facing the same issue.

**Comment by jacobkahn** [comment]
Fixed in https://github.com/flashlight/sequence/pull/20
