### ISSUE TITLE
Add distributed stub

### ISSUE THREAD

**Issue by lunixbochs** [flashlight/flashlight#496]
### Feature Description
Flashlight apps require distributed mode. CPU distributed mode (Gloo) is only available on Linux, so flashlight apps won't compile easily for Mac (and probably Windows, I'm not there yet).

My solution right now is to add another distributed mode, "stub", which implements the API with a hardcoded world size of 1. This removes the need to ever disable distributed mode APIs.

#### Use Case
I want to build and distribute flashlight + apps with the CPU backend for Mac/Windows, which currently requires me to patch distributed mode as that's not available on non-Linux.

#### Additional Context
I've implemented a distributed stub here:
https://github.com/talonvoice/flashlight/commit/7e28e66b875a737759f09131d45a415bc089520a

With this change, you could probably remove `-DFL_BUILD_DISTRIBUTED=OFF` support entirely, and instead set the distributed backend like`-DFL_BACKEND=CPU -DFL_DISTRIBUTED_MODE=STUB`

**Comment by tlikhomanenko** [comment]
cc @jacobkahn your thoughts? I think it looks good!

Thanks @lunixbochs!

**Comment by jacobkahn** [comment]
@lunixbochs — if you ever wanted to rebase and send a PR for this, we'd welcome that :)

**Comment by tlikhomanenko** [comment]
merged https://github.com/flashlight/flashlight/pull/614
