### ISSUE TITLE
Can I use "fl_asr_train continue" to continue the trainig of the model finetuned with fl_asr_tutorial_finetune_ctc?

### ISSUE THREAD

**Issue by tyalamov** [flashlight/flashlight#501]
I have a trained conformer model. I tried to finetune it by adding more data and using fl_asr_tutorial_finetune_ctc instead of "fl_asr_train continue". The finetuning works and I can use the new model with fl_asr_test and fl_asr_decode. The emission and decoding works fine, but I can't use "fl_asr_train continue" to continue the new training. The loading of the model from fl_asr_train fails with:

E0319 12:08:02.900834 03008 Serializer.h:80 Error while loading "finetune/001_model_last.bin": Failed to read 4 bytes from input stream! Read 0

Is the continuation of the training of finetuned model supposed to works or it's unsupported?

**Comment by tlikhomanenko** [comment]
Hey! It should work. Probably there is just problem with flags parsing. Can you print log with flags for both calls: fl_asr_train continue and fl_asr_tutorial_finetune_ctc?

**Comment by tlikhomanenko** [comment]
Feel free to reopen if the problem is still there. Also please add more details on log.
