### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by DandelionYoungL** [flashlight/flashlight#503]
### problem:
test the decoder using the example.
**command:**
python bindings/python/example/decoder_example.py  flashlight/app/asr/test/decoder/data/

Loading the LM will be faster if you build a binary file.                                                         Reading flashlight/app/asr/test/decoder/data/lm.arpa                                                              ----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100              ****************************************************************************************************              Segmentation fault 

### configuration:
flashligth: 1.0.0
eigen: 3.3.9
fftw:3.3.9
boost: 1.53.0
gcc/g++ 5.4.0
cmake 3.20.0
python: 3.6
torch version: 1.5.0+cuda90_cudnn7.6.3_lms

### install steps
**eigen**
wget https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz
makedir build & cd build
cmake ..
make install

**kenlm**
git clone https://github.com/kpu/kenlm
mkdir build & cd build
cmake ..
make -j16

**fftw**
git clone http://fftw.org/fftw-3.3.9.tar.gz
cmake .
make 
make install

flashlight:
git clone https://github.com/facebookresearch/flashlight.git && cd flashlight/bindings/python
export USE_CUDA=0
export USE_MKL=0
pip install -e .

the kenlm can work well.

**Comment by DandelionYoungL** [comment]
> Could you try to add
> 
> ```
> export KENLM_ROOT=[path to your kenlm clone]
> ```
> 
> remove the build dir in bindings/python and run pip install again?

I try it, still segmentation fault. 
when compile the flashlight, need c++11? 
when i cmake the kenlm, I add "set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0")
set(CMAKE_CXX_STANDARD 11) " to the CMakeLists.txt
If not c++11, complile the kenlm, would get errors about boost.

**Comment by tlikhomanenko** [comment]
flashlight is c++14 https://github.com/facebookresearch/flashlight/blob/master/CMakeLists.txt#L15. What kind of boost errors do you have? I think then problem in your boost version. Can you try later ones so that kenlm is compiled without any hacks into its cmake?

**Comment by jacobkahn** [comment]
@DandelionYoungL — if you're having trouble compiling KenLM, you should post an issue in that repo accordingly — https://github.com/kpu/kenlm.
