### ISSUE TITLE
ASR building: cmake tries to build Object Detection app too

### ISSUE THREAD

**Issue by MBichurin** [flashlight/flashlight#528]
### Bug Description
Following instructions from [the Colab notebook](https://colab.research.google.com/github/facebookresearch/flashlight/blob/master/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb) leads to cmake errors caused by lack of the 'DFL_BUILD_APP_OBJDET' attribute.

#### Reproduction Steps
- Follow the Colab notebook instructions up to the ASR building line

#### Additional Context
Right now the cmake command looks like this:
`cmake .. -DFL_BACKEND=CPU -DCMAKE_BUILD_TYPE=Release -DFL_BUILD_TESTS=OFF -DFL_BUILD_EXAMPLES=OFF -DFL_BUILD_APP_IMGCLASS=OFF -DFL_BUILD_APP_LM=OFF`

However, this makes my machine try to build both ASR and ObjDet. But there're not enough files for the second one, so building of both fails.

The proper configuration now should look like this:
`cmake .. -DFL_BACKEND=CPU -DCMAKE_BUILD_TYPE=Release -DFL_BUILD_TESTS=OFF -DFL_BUILD_EXAMPLES=OFF -DFL_BUILD_APP_IMGCLASS=OFF -DFL_BUILD_APP_LM=OFF -DFL_BUILD_APP_OBJDET=OFF`

Btw is there any way to prevent this in the future? I mean it would be cool to say "build ASR only" without mentioning every other application.

_P.S.: Congrats for adding a new app in the repository. Please, update the ASR tutorial_

**Comment by jacobkahn** [comment]
@MBichurin thanks for reporting, cc @padentomasello.

A sensible thing to do would be to make app building opt-in since there are so many of them now -- and have all of the default to `OFF`. We'll discuss internally! Thanks again.

**Comment by jacobkahn** [comment]
Fixed in #533. Thanks again for the suggest @MBichurin.
