### ISSUE TITLE
python bindings setup install error

### ISSUE THREAD

**Issue by izzajalandoni** [flashlight/flashlight#535]
### Bug Description
Installed the dependencies -- i.e. KenLM, OpenBLAS, FFTW3 -- accordingly before running `python setup.py install`. However, I got the following error:

running install
running bdist_egg
running egg_info
writing flashlight.egg-info/PKG-INFO
writing dependency_links to flashlight.egg-info/dependency_links.txt
writing top-level names to flashlight.egg-info/top_level.txt
package init file 'flashlight/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
reading manifest file 'flashlight.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'flashlight.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.9
creating build/lib.linux-x86_64-3.9/flashlight
creating build/lib.linux-x86_64-3.9/flashlight/lib
copying flashlight/lib/__init__.py -> build/lib.linux-x86_64-3.9/flashlight/lib
creating build/lib.linux-x86_64-3.9/flashlight/lib/audio
copying flashlight/lib/audio/feature.py -> build/lib.linux-x86_64-3.9/flashlight/lib/audio
creating build/lib.linux-x86_64-3.9/flashlight/lib/sequence
copying flashlight/lib/sequence/criterion.py -> build/lib.linux-x86_64-3.9/flashlight/lib/sequence
copying flashlight/lib/sequence/criterion_torch.py -> build/lib.linux-x86_64-3.9/flashlight/lib/sequence
creating build/lib.linux-x86_64-3.9/flashlight/lib/text
copying flashlight/lib/text/dictionary.py -> build/lib.linux-x86_64-3.9/flashlight/lib/text
copying flashlight/lib/text/decoder.py -> build/lib.linux-x86_64-3.9/flashlight/lib/text
running build_ext
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- -rdynamic supported.
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CUDA found (library: /usr/local/cuda-10.2/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda-10.2/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_75,code=compute_75
-- Will build flashlight libraries.
-- MKL_THREADING = OMP
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - found
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
CMake Error at /usr/local/lib/cmake/fftw3/FFTW3Config.cmake:13 (include):
  include could not find load file:

    /usr/local/lib/cmake/fftw3/FFTW3LibraryDepends.cmake
Call Stack (most recent call first):
  cmake/FindFFTW3.cmake:22 (find_package)
  flashlight/lib/audio/feature/CMakeLists.txt:17 (find_package)
  flashlight/lib/audio/CMakeLists.txt:6 (include)
  flashlight/lib/CMakeLists.txt:31 (include)
  CMakeLists.txt:134 (include)

-- FFTW found
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Looking for KenLM
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Found LibLZMA: /usr/include (found version "5.2.2") 
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Using kenlm library found in /usr/local/lib/libkenlm.a
-- Using kenlm utils library found in /usr/local/lib/libkenlm_util.a
-- kenlm model.hh found in /usr/local/include/kenlm/lm
-- Found kenlm: /usr/local/include  
-- Found kenlm (include: /usr/local/include, library: /usr/local/lib/libkenlm.a;/usr/local/lib/libkenlm_util.a;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)
-- Could NOT find cub (missing: cub_INCLUDE_DIRS) 
-- Could not find cub - will download from source
-- Found PythonInterp: /home/airscan/anaconda2/envs/fairseq/bin/python (found version "3.9.2") 
-- Found PythonLibs: /home/airscan/anaconda2/envs/fairseq/lib/libpython3.9.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring incomplete, errors occurred!
See also "/home/airscan/libs/flashlight/bindings/python/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeOutput.log".
See also "/home/airscan/libs/flashlight/bindings/python/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/home/airscan/libs/flashlight/bindings/python/setup.py", line 111, in <module>
    setup(
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/airscan/libs/flashlight/bindings/python/setup.py", line 56, in run
    self.build_extensions(ext)
  File "/home/airscan/libs/flashlight/bindings/python/setup.py", line 105, in build_extensions
    subprocess.check_call(
  File "/home/airscan/anaconda2/envs/fairseq/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/airscan/libs/flashlight', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/airscan/libs/flashlight/bindings/python/build/lib.linux-x86_64-3.9', '-DPYTHON_EXECUTABLE=/home/airscan/anaconda2/envs/fairseq/bin/python', '-DFL_BUILD_STANDALONE=OFF', '-DBUILD_SHARED_LIBS=ON', '-DFL_BUILD_LIBRARIES=ON', '-DFL_BUILD_CORE=OFF', '-DFL_BUILD_TESTS=OFF', '-DFL_BUILD_EXAMPLES=OFF', '-DFL_BACKEND=CUDA', '-DFL_LIBRARIES_BUILD_FOR_PYTHON=ON', '-DFL_LIBRARIES_USE_CUDA=ON', '-DFL_LIBRARIES_USE_KENLM=ON', '-DFL_LIBRARIES_USE_MKL=ON', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

#### Reproduction Steps
Simply followed the installation steps:
python setup.py install

### Platform and Hardware
OS: Ubuntu 18.04.3 LTS
GPU: GeForce GTX 1080
CUDA Version: 10.2
Python Version: 3.9.2
Torch Version: 1.8.1
GCC: 7.3.0
cmake: 3.10.2

#### Additional Context
Haven't installed Flashlight itself. However, if my understanding is correct, it does say in the README of bindings that it is not required.

Any guidance would be appreciated. Thank you!

**Comment by tlikhomanenko** [comment]
Hey! Did you run `apt-get install libfftw3-dev`? If not, could you try it and give another try to install bindings?

Yes, you don't need to build full fl for python bindings.

**Comment by izzajalandoni** [comment]
@tlikhomanenko Hello! Apologies for the late reply, and thanks for the response! Yes, it was already installed before running setup.py. Is the fftw cmake necessary? Not sure what else I'm missing here.

**Comment by izzajalandoni** [comment]
@tlikhomanenko Hello! Apologies for the late reply, and thanks for the response! Yes, it was already installed before running setup.py. Is the fftw cmake necessary? Not sure what else I'm missing here.

**Comment by izzajalandoni** [comment]
Not sure but I think the problem is the threading. I tried with vcpkg and I still got the same configuration error prompt, with the ff log:

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/airscan/libs/flashlight/bindings/python/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_257bd/fast"
/usr/bin/make -f CMakeFiles/cmTC_257bd.dir/build.make CMakeFiles/cmTC_257bd.dir/build
make[1]: Entering directory '/home/airscan/libs/flashlight/bindings/python/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_257bd.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_257bd.dir/CheckSymbolExists.c.o   -c /home/airscan/libs/flashlight/bindings/python/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_257bd
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_257bd.dir/link.txt --verbose=1
/usr/bin/cc      CMakeFiles/cmTC_257bd.dir/CheckSymbolExists.c.o  -o cmTC_257bd 
CMakeFiles/cmTC_257bd.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_257bd.dir/build.make:97: recipe for target 'cmTC_257bd' failed
make[1]: *** [cmTC_257bd] Error 1
make[1]: Leaving directory '/home/airscan/libs/flashlight/bindings/python/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_257bd/fast' failed
make: *** [cmTC_257bd/fast] Error 2

File /home/airscan/libs/flashlight/bindings/python/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

This was suppose to be longer, but same gist of error (ie being `undefined reference to pthread_create`). It shortened to that when I added in `set(THREADS_PREFER_PTHREAD_FLAG ON)` on flashlight's CMakeLists. But still wasn't able to completely silence it. Not sure if I should manually link it to all executables. Would appreciate guidance on this one.

**Comment by tlikhomanenko** [comment]
Can you check if you have /usr/local/lib/cmake/fftw3/FFTW3LibraryDepends.cmake? Also do you use conda env? 

About vcpkg - I don't think it will work as it is, you need to add in setup.py then the toolchain path to your vcpkg deps.

About fft3 - you don't need to run cmake for it, apt-get should be enough.

cc @jacobkahn do you have any idea what could be else wrong?

**Comment by izzajalandoni** [comment]
Good day! Apologies for this very late reply. Indeed, the problem was fftw3, previously installed it through configure, which did not generate the FFTW3LibraryDepends.cmake file. Reinstalled it through cmake, and bindings now installed properly. Thanks!

**Comment by webbp** [comment]
Caused by https://github.com/FFTW/fftw3/issues/130
