### ISSUE TITLE
[Nodejs bindings]

### ISSUE THREAD

**Issue by loretoparisi** [flashlight/flashlight#542]
### Feature Description
Any plan to add bindings to NodeJS (SWIG interfaces or native nodejs module addon, or even Emscripten)?

#### Use Case
Running NodeJS web applications

#### Additional Context
Currently NodeJS lacks of a proper ML standalone library. The only option is Tensorflow.js that uses the Tensorflow C++ core apis, but the TF api in Node is limited.

**Comment by loretoparisi** [comment]
Thanks, let me have a look at flashlight header files. It's the starting point for the bindings.

**Comment by lengoanhcat** [comment]
@loretoparisi : have you had any further comment on the possibility of creating a js binding for flashlight ?

**Comment by jacobkahn** [comment]
@loretoparisi @lengoanhcat -- we've recently spun off Shumai (https://github.com/facebookresearch/shumai) which binds Flashlight to the Bun Javascript; we're in the process of building NodeJS bindings as well.

**Comment by loretoparisi** [comment]
> @loretoparisi @lengoanhcat -- we've recently spun off Shumai (https://github.com/facebookresearch/shumai) which binds Flashlight to the Bun Javascript; we're in the process of building NodeJS bindings as well.

that's amazing gift, thank you and happy new 2023 in advance! 🎊🥳🎉
