### ISSUE TITLE
CMake build, issue with linking ArrayFire, CPU build

### ISSUE THREAD

**Issue by mboros1** [flashlight/flashlight#555]
### Bug Description
Installed all dependencies, CMake output is showing the ArrayFire afcpu library found, getting linker error for ArrayFire::afcpu

#### Reproduction Steps
ran `cmake .. -DCMAKE_INCLUDE_PATH=/home/myhome/.local/include/ -DFL_BACKEND=CPU`

Added my local include path based on using mkl headers from pip

### Platform and Hardware
Ubuntu 20.04, Intel CPU

#### Additional Context
CMake output attached below
[cmake_errors.txt](https://github.com/flashlight/flashlight/files/6347136/cmake_errors.txt)

**Comment by jacobkahn** [comment]
@mboros1 — can you paste the contents of the `ArrayFireCPUTargets.cmake` file should should be located in `[your ArrayFire install prefix]/share/ArrayFire/cmake`?

Also — you built ArrayFire from source, correct?

**Comment by mboros1** [comment]
I was using the apt package for ArrayFire cpu, tried again after building ArrayFire  from source and it now compiled successfully

**Comment by jacobkahn** [comment]
@mboros1 - got it - the ArrayFire apt package doesn't seem to be maintained or up to date. Glad everything is working.
