### ISSUE TITLE
CMake build, some targets fail linking `sycl`

### ISSUE THREAD

**Issue by mboros1** [flashlight/flashlight#558]
### Bug Description
When building some of the targets, getting linker error on `sycl`

Not seeing this as a dependency, any advice on where to get this library?

#### Reproduction Steps

CMake command:
`cmake .. -DCMAKE_INCLUDE_PATH=/home/myhome/.local/include/ -DFL_BACKEND=CPU `

No errors, when building with make I get linker error pasted below

[ 94%] Linking CXX executable Benchmark
/usr/bin/ld: cannot find -lsycl
collect2: error: ld returned 1 exit status
make[2]: *** [flashlight/fl/examples/CMakeFiles/Benchmark.dir/build.make:104: flashlight/fl/examples/Benchmark] Error 1
make[1]: *** [CMakeFiles/Makefile2:1074: flashlight/fl/examples/CMakeFiles/Benchmark.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 94%] Linking CXX executable RnnLm
[ 94%] Linking CXX executable Perceptron
/usr/bin/ld: cannot find -lsycl
collect2: error: ld returned 1 exit status
make[2]: *** [flashlight/fl/examples/CMakeFiles/RnnLm.dir/build.make:104: flashlight/fl/examples/RnnLm] Error 1
make[1]: *** [CMakeFiles/Makefile2:1158: flashlight/fl/examples/CMakeFiles/RnnLm.dir/all] Error 2
/usr/bin/ld: cannot find -lsycl
collect2: error: ld returned 1 exit status
make[2]: *** [flashlight/fl/examples/CMakeFiles/Perceptron.dir/build.make:104: flashlight/fl/examples/Perceptron] Error 1
make[1]: *** [CMakeFiles/Makefile2:1130: flashlight/fl/examples/CMakeFiles/Perceptron.dir/all] Error 2
[ 94%] Linking CXX executable Mnist
/usr/bin/ld: cannot find -lsycl
collect2: error: ld returned 1 exit status
make[2]: *** [flashlight/fl/examples/CMakeFiles/Mnist.dir/build.make:104: flashlight/fl/examples/Mnist] Error 1
make[1]: *** [CMakeFiles/Makefile2:1102: flashlight/fl/examples/CMakeFiles/Mnist.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

### Platform and Hardware
Ubuntu 20.04, Intel CPU

**Comment by jacobkahn** [comment]
@mboros1 Can you confirm the path where libsycl is installed? It's failing to link, but this should be caught when running CMake...

**Comment by mboros1** [comment]
I do not have libsycl installed; is it part of a dependency that I'm missing? Sorry, trying to find out what it is but not having much luck

**Comment by jacobkahn** [comment]
@mboros1 — you'll need to have `libsycl` - that's the linker error. CMake should surface something nicer, but it's not (sorry)...

Do you have Intel MKL installed? The library should be in a path like `/opt/intel/inteloneapi/compiler/latest/linux/lib/libsycl.so` depending on where you installed MKL...

**Comment by mboros1** [comment]
@jacobkahn okay thanks for the tip, CMake was getting confused by a version of MKL installed as an apt package. Removed it, set `export MKLROOT=/opt/intel/oneapi/mkl/latest` and now CMake is finding the correct MKL package. However, I still have the same linker error: 

[ 76%] Linking CXX executable AutogradTest
/usr/bin/ld: cannot find -lsycl
collect2: error: ld returned 1 exit status
make[2]: *** [flashlight/fl/test/CMakeFiles/MeterTest.dir/build.make:109: flashlight/fl/test/MeterTest] Error 1
make[1]: *** [CMakeFiles/Makefile2:1581: flashlight/fl/test/CMakeFiles/MeterTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lsycl
collect2: error: ld returned 1 exit status
make[2]: *** [flashlight/fl/test/CMakeFiles/DatasetUtilsTest.dir/build.make:109: flashlight/fl/test/DatasetUtilsTest] Error 1
make[1]: *** [CMakeFiles/Makefile2:1609: flashlight/fl/test/CMakeFiles/DatasetUtilsTest.dir/all] Error 2
/usr/bin/ld: cannot find -lsycl
collect2: error: ld returned 1 exit status
make[2]: *** [flashlight/fl/test/CMakeFiles/AutogradTest.dir/build.make:109: flashlight/fl/test/AutogradTest] Error 1
make[1]: *** [CMakeFiles/Makefile2:1637: flashlight/fl/test/CMakeFiles/AutogradTest.dir/all] Error 2
/usr/bin/ld: cannot find -lsycl
collect2: error: ld returned 1 exit status
make[2]: *** [flashlight/fl/test/CMakeFiles/ContribSerializationTest.dir/build.make:109: flashlight/fl/test/ContribSerializationTest] Error 1
make[1]: *** [CMakeFiles/Makefile2:1553: flashlight/fl/test/CMakeFiles/ContribSerializationTest.dir/all] Error 2
make: *** [Makefile:141: all] Error 2


I found `libsycl.so`, but my path is slightly different, `/opt/intel/oneapi/mkl/latest/lib/intel64`, but still my CMake output:

-- MKL_THREADING = OMP
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- MKL library found

Seems like it should be on the library path. Any thoughts?

**Comment by mboros1** [comment]
I missed a step configuring OneAPI: `. /opt/intel/oneapi/setvars.sh` sets up all the environment variables for the SYCL toolchain, getting a different linker error now but it's unrelated to this

**Comment by jacobkahn** [comment]
@mboros1 good to know -- thanks for sharing that... that's a weird setup step. Feel free to open another issue if you're having trouble linking other things.

**Comment by mboros1** [comment]
@jacobkahn thanks for the help, tough project to build but I found out the last step I was missing and for the sake of documentation for the next person searching the issues, the error was:

`DistributedBackend.cpp:(.text+0x18d): undefined reference to `gloo::mpi::Context::createManaged()'`

Caused because I did not build gloo with MPI, fixed with `USE_MPI=ON` which is mentioned in build documentation here. Now I can finally test it out!
