### ISSUE TITLE
How can I increase Trie label number reached limit?

### ISSUE THREAD

**Issue by wwj8837817** [flashlight/flashlight#565]
Trie label number reached limit: 6

I'm using "wav2letter/recipes/streaming_convnets", and I need to increase it,but how? 
I modified the source code and recompiled（cmake & make & make install） it, but it didn't work..

**Comment by tlikhomanenko** [comment]
Hey! Did you change this constant https://github.com/flashlight/flashlight/blob/master/flashlight/lib/text/decoder/Trie.h#L17 and then recompiled? If yes, what value did you set? Do you see the same message in the log that limit is 6?

**Comment by wwj8837817** [comment]
Thank you very much for your contribution and reply.
It's all right in fl_asr_tutorial_inference_ctc.
but not valid for flashlight/wav2letter/blob/master/recipes/streaming_convnets/inference/inference/examples/MultithreadedStreamingASRExample.cpp.

**Comment by wwj8837817** [comment]
Thank you very much for your contribution and reply.
I changed this constant https://github.com/flashlight/flashlight/blob/master/flashlight/lib/text/decoder/Trie.h#L17 and then recompiled.
Then it's all right in fl_asr_tutorial_inference_ctc.
but not valid for flashlight/wav2letter/blob/master/recipes/streaming_convnets/inference/inference/examples/MultithreadedStreamingASRExample.cpp. I don't know why.

**Comment by wwj8837817** [comment]
root@f34be79b7213:~# find / -name Trie.h
/opt/flashlight/include/flashlight/lib/text/decoder/Trie.h
/root/flashlight/flashlight/lib/text/decoder/Trie.h
/usr/local/include/flashlight/lib/text/decoder/Trie.h
**(All of the above Trie.h has been changed)**
root@f34be79b7213:~# cat /root/flashlight/flashlight/lib/text/decoder/Trie.h | head -n 18
/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

#pragma once
#include <memory>
#include <unordered_map>
#include <vector>

namespace fl {
namespace lib {
namespace text {

constexpr int kTrieMaxLabel = 60;

**Comment by tlikhomanenko** [comment]
Did you recompile also wav2letter inference pipeline?

**Comment by wwj8837817** [comment]
I recompiled “~/wav2letter/recipes/streaming_convnets/inference/build”  several times. Maybe I made a mistake before. I have compiled it successfully now. Thank you very much for your timely and patient guidance

**Comment by tlikhomanenko** [comment]
Then closing the issue.
