### ISSUE TITLE
Unable to include Flashlight using CMAKE installed via vcpkg

### ISSUE THREAD

**Issue by HarrisDePerceptron** [flashlight/flashlight#574]
### Bug Description
installed flashligh through vcpkg. the current install version is `0.3`  unable to successfully  include/integrate  flashlight core with cmake

#### Reproduction Steps
`./vcpkg install flashlight-cpu`
after installation the vcpkg instructions says

```
The package flashlight-cpu:x64-linux provides CMake targets:
find_package(flashlight-cpu CONFIG REQUIRED)
target_link_libraries(main PRIVATE flashlight::flashlight)
```

when you  try to `find_package(flashlight-cpu CONFIG REQUIRED)` in cmake:
```
[cmake] CMake Error at /home/firefrog/vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package):
[cmake]   Could not find a package configuration file provided by "flashlight-cpu"
[cmake]   with any of the following names:
[cmake] 
[cmake]     flashlight-cpuConfig.cmake
[cmake]     flashlight-cpu-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "flashlight-cpu" to CMAKE_PREFIX_PATH or set
[cmake]   "flashlight-cpu_DIR" to a directory containing one of the above files.  If
[cmake]   "flashlight-cpu" provides a separate development package or SDK, be sure it
[cmake]   has been installed.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:14 (find_package)
```

when you  try to use  `find_package(flashlight CONFIG REQUIRED)` in cmake  as mentioned in the readme example:

```
cmake] CMake Error at /home/firefrog/vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package):
[cmake]   By not providing "Findkenlm.cmake" in CMAKE_MODULE_PATH this project has
[cmake]   asked CMake to find a package configuration file provided by "kenlm", but
[cmake]   CMake did not find one.
[cmake] 
[cmake]   Could not find a package configuration file provided by "kenlm" with any of
[cmake]   the following names:
[cmake] 
[cmake]     kenlmConfig.cmake
[cmake]     kenlm-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "kenlm" to CMAKE_PREFIX_PATH or set
[cmake]   "kenlm_DIR" to a directory containing one of the above files.  If "kenlm"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
```

I have also installed  `kenlm` via vcpkg:
```
$ ./vcpkg install kenlm
The following packages are already installed:
  kenlm[core]:x64-linux -> 20200924#1
Package kenlm:x64-linux is already installed

```
### Platform and Hardware
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

```

```
$  uname -s -r -v -m -o
Linux 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 GNU/Linux
```

```
$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

```

```
$ cmake --version
cmake version 3.10.2
```

```
$ ./vcpkg version
Vcpkg package management program version 2021-01-13-unknownhash

```

#### Additional Context
Installed intel oneapi for intel-oneapi-mkl and intel-oneapi-mkl-devel before running the vcpkg installation

**Comment by jacobkahn** [comment]
@HarrisDePerceptron thanks for the thorough details. I have a repro. Looks like the underlying KenLM port has changed a bit. I'll dive in today and send a port update or fix.

**Comment by HarrisDePerceptron** [comment]
@jacobkahn  what are steps since you seemed to have fixed it

**Comment by wolwalstud** [comment]
Hello, I have somewhat the same problem:

    cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/wolfram/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release
    -- Found OpenMP_C: -fopenmp  
    -- Found OpenMP_CXX: -fopenmp  
    -- Found OpenMP: TRUE   
    CMake Error at /home/wolfram/vcpkg/scripts/buildsystems/vcpkg.cmake:764 (_find_package):
      By not providing "Findkenlm.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "kenlm", but
      CMake did not find one.
    
      Could not find a package configuration file provided by "kenlm" with any of
      the following names:
    
        kenlmConfig.cmake
        kenlm-config.cmake
    
      Add the installation prefix of "kenlm" to CMAKE_PREFIX_PATH or set
      "kenlm_DIR" to a directory containing one of the above files.  If "kenlm"
      provides a separate development package or SDK, be sure it has been
      installed.
    Call Stack (most recent call first):
      /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
      /home/wolfram/vcpkg/installed/x64-linux/share/flashlight/flashlightConfig.cmake:28 (find_dependency)
      /home/wolfram/vcpkg/scripts/buildsystems/vcpkg.cmake:764 (_find_package)
      CMakeLists.txt:9 (find_package)
    
    
    -- Configuring incomplete, errors occurred!


kenlm is also installed:

    Computing installation plan...
    The following packages are already installed:
        kenlm[core]:x64-linux -> 20200924#1
    Package kenlm:x64-linux is already installed
    
    Total elapsed time: 9.568 us
    
 ### Platform and Hardware
 
     $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04.2 LTS
    Release:	20.04
    Codename:	focal

    $ uname -s -r -v -m -o
    Linux 5.11.10-051110-generic #202103251032 SMP Thu Mar 25 10:35:48 UTC 2021 x86_64 GNU/Linux

    $ cmake --version
    cmake version 3.16.3

    $ gcc --version
    gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

    $./vcpkg/vcpkg version
    Vcpkg package management program version 2021-05-05-unknownhash


I hope i didnt miss a fix or something.
