### ISSUE TITLE
linux AMD CPU install flashlight

### ISSUE THREAD

**Issue by wilambatch** [flashlight/flashlight#580]
When will it be compatible with AMD CPU backend？
Intel MKL is not very compatible with AMD cpu；how to solve this problem？

**Comment by tlikhomanenko** [comment]
cc @jacobkahn @andresy

**Comment by jacobkahn** [comment]
@wilambatch — there's an experimental OpenCL backend available now that you can try. We aren't supporting it and may remove it in a future release.
