### ISSUE TITLE
Feeding Audio file directly to fl_asr_tutorial_inference_ctc

### ISSUE THREAD

**Issue by MHumza3656** [flashlight/flashlight#583]
### Question
We currently feed the path of our audio files that are then loaded and inference by the model. Is there a way to send an audio file, loaded in python, directly for the inference?

#### Additional Context
The need for this is genuine since we can't feed a large audio file to the model. We have to cut the audio file, and for now, I store each cut file and then feed the model its path.

**Comment by tlikhomanenko** [comment]
We don't have the python wrapper for model forward, so you have two options:
1) You do python process which cut the audio and store chunk  intp tmp file then feed to the inference process the path
2) You tweak the inference cpp file to cut the file into chunks, do forward and print output for every chunk.

**Comment by MHumza3656** [comment]
Right makes sense. Since loading raw audio files can be of any format and I checked that the code does check the specifications of the audio file. Does it convert the audio file to relevant specifications as well or only checks it?

**Comment by tlikhomanenko** [comment]
Depending on what params you provided it compute necessary features from raw wave (or use raw wave if needed) and then you can cut into chunks the audio and call proper forward pass. Does this make sense? Let me know if you need any code pointers.

**Comment by MHumza3656** [comment]
So, the cutting into chunks part is handled a bit logically that I did write in python but I don't know if the implementation for me on C++ would be possible
For now, I extracted a raw_data (in Bytes) from python and sent that through `stdin.write` param. I have verified that I'm receiving those bytes at my C++ code but I really don't know how to read those bytes in ifstream for the next process to continue. Example of those bytes is this `b'\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x`

**Comment by sebtrack** [comment]
I need the same functionality. Unfortunately, the `InferenceCTC.cpp` can only handle files. I found the code for the streaming inference [SimpleStreamingASRExample.cpp](https://github.com/flashlight/wav2letter/blob/v0.2/inference/inference/examples/SimpleStreamingASRExample.cpp) much better written, it can also handle stdin input. I'm going to try to fuse them. 

Is there a reason why `InferenceCTC` not using the [DecoderFactory](https://github.com/flashlight/wav2letter/blob/v0.2/inference/inference/decoder/Decoder.cpp) and is building everything on its own?

**Comment by tlikhomanenko** [comment]
Decoder factory was written for online inference, while in InferenceCTC we do not need online with fixed history and we simply use standard decoder classes. InferenceCTC is just an example how you can write your own executable file with forward + decoder. Feel free to adapt and create your own executable file.

**Comment by tlikhomanenko** [comment]
@MHumza3656 please google how to communicate between different processes and/or how to read bytes in c++.
