### ISSUE TITLE
Errors while running CTest

### ISSUE THREAD

**Issue by samin9796** [flashlight/flashlight#586]
I am using flashlight docker with CPU backend. The following tests have failed. I get "loss value NaN" error during training. Could you please provide any solution? 

*** I am using Ubuntu 20.04
 

> 99% tests passed, 4 tests failed out of 374
> 
> Total Test time (real) = 240.04 sec
> 
> The following tests did not run:
> 	207 - DatasetTest.PrefetchDatasetPerformance (Disabled)
> 
> The following tests FAILED:
> 	333 - TextDatasetTest.NoneMode (Failed)
> 	334 - TextDatasetTest.EosMode (Failed)
> 	335 - TextDatasetTest.EosModeWithDynamicBatching (Failed)
> 	344 - SetCriterion.DifferentNumberOfLabelsClass (Failed)
> Errors while running CTest
> make: *** [Makefile:107: test] Error 8

**Comment by tlikhomanenko** [comment]
Do you have problems with recent master?

**Comment by samin9796** [comment]
I am having problems with the flml/flashlight:cpu-latest docker image that has been pushed just 4 days ago. I saw that the flashlight docker images are for Ubuntu 18.04 and Cuda-10.0 somewhere in the documentation. Is it because I am using Ubuntu 20.04?

**Comment by tlikhomanenko** [comment]
It doesn't matter what ubuntu version you have as docker is independent on this (only cuda drivers are used by it, but the rest is encapsulated inside the docker). Let me check tests on CPU docker locally.

**Comment by tlikhomanenko** [comment]
I just pulled current latest docker and run all tests inside
```
100% tests passed, 0 tests failed out of 328

Total Test time (real) = 1768.47 sec

The following tests did not run:
        206 - DatasetTest.PrefetchDatasetPerformance (Disabled)
root@1233caadbf9f:~/flashlight/build#
```

Seems you have problem somewhere else. Could you run each individual test separately to see what exactly the error?

**Comment by samin9796** [comment]
Could you please tell me how to perform individual tests?

**Comment by tlikhomanenko** [comment]
Inside the build directory run
```
./flashlight/app/lm/test/TextDatasetTest
```

**Comment by samin9796** [comment]
After running `./flashlight/app/lm/test/TextDatasetTest`, I got the following:

>  [==========] Running 3 tests from 1 test suite.
> [----------] Global test environment set-up.
> [----------] 3 tests from TextDatasetTest
> [ RUN      ] TextDatasetTest.NoneMode
> unknown file: Failure
> C++ exception with description "std::bad_alloc" thrown in the test body.
> [  FAILED  ] TextDatasetTest.NoneMode (2 ms)
> [ RUN      ] TextDatasetTest.EosMode
> unknown file: Failure
> C++ exception with description "std::bad_alloc" thrown in the test body.
> [  FAILED  ] TextDatasetTest.EosMode (0 ms)
> [ RUN      ] TextDatasetTest.EosModeWithDynamicBatching
> unknown file: Failure
> C++ exception with description "std::bad_alloc" thrown in the test body.
> [  FAILED  ] TextDatasetTest.EosModeWithDynamicBatching (0 ms)
> [----------] 3 tests from TextDatasetTest (2 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 3 tests from 1 test suite ran. (2 ms total)
> [  PASSED  ] 0 tests.
> [  FAILED  ] 3 tests, listed below:
> [  FAILED  ] TextDatasetTest.NoneMode
> [  FAILED  ] TextDatasetTest.EosMode
> [  FAILED  ] TextDatasetTest.EosModeWithDynamicBatching

**Comment by tlikhomanenko** [comment]
And you see this while running in docker image?

**Comment by samin9796** [comment]
Yes, I am running in docker image

**Comment by jacobkahn** [comment]
@samin9796 looks like your Docker VM is out of memory. Can you monitor memory usage during the test and confirm this?

**Comment by samin9796** [comment]
During the test, I used `gnome-system-monitor` to watch the memory usage. It is always less than 30% of the total memory that has been used. I have a total of 16 GB RAM. CPU usage also seems to be fine.

**Comment by tlikhomanenko** [comment]
Are you training LM or ASR? These test are related to LM data preparation, so in case you train ASR you can skip them. For your issue loss is Nan did you test other parameters of training and (if possible) running on GPU?

**Comment by sahilg06** [comment]
I am also using flashlight docker with CPU backend (in Macbook air M1chip). In my case, these tests failed. Can you please solve the issue?
<img width="856" alt="Screenshot 2021-06-01 at 19 42 12" src="https://user-images.githubusercontent.com/59660566/120338334-c3b1c580-c311-11eb-9a4a-86b1c1dfef0f.png">

**Comment by tlikhomanenko** [comment]
> I am also using flashlight docker with CPU backend (in Macbook air M1chip). In my case, these tests failed. Can you please solve the issue?@tlikhomanenko
> <img alt="Screenshot 2021-06-01 at 19 42 12" width="856" src="https://user-images.githubusercontent.com/59660566/120338334-c3b1c580-c311-11eb-9a4a-86b1c1dfef0f.png">

Can you run each of the failed test separately and post result here?
