### ISSUE TITLE
MPI P2P Communication Protocol

### ISSUE THREAD

**Issue by raj-brown** [flashlight/flashlight#602]
Dear All-
Is there any way to use point 2 point communication protocol of MPI?  I mean like. `MPI.Send` and `MPI.Recv` and `MPI.Isend` or `MPI.Irecv`.

Thanks!
Regards
Raj

**Comment by tlikhomanenko** [comment]
For what purposes you wanna to do this? Better to ask directly in MPI project.

**Comment by raj-brown** [comment]
@tlikhomanenko As mentioned in distributed training computing section, there are api for allreduce and broadcast and I wondered if there are APIs for `MPI.Isend ` and `MPI.Irecv` for tensor in FLashlight.

**Comment by tlikhomanenko** [comment]
cc @jacobkahn

**Comment by jacobkahn** [comment]
@raj-brown we don't have p2p API components in Flashlight's distributed API, but you can easily add those MPI functions yourself — if you've built Flashlight with distributed functionality, you can include `<mpi.h>`, call those functions yourself, and and go from there.
