### ISSUE TITLE
Online Decoding of Speech Input to Microphone

### ISSUE THREAD

**Issue by gevorgyana** [flashlight/flashlight#613]
### Question
I want to have wav2letter process speech as it is being spoken into a microphone. Is it possible at the moment? Could you include a tutorial on doing so in the documentation?
#### Additional Context
Here is a link to the discussion: https://github.com/flashlight/flashlight/discussions/601
@tlikhomanenko could you please have a look?

**Comment by tlikhomanenko** [comment]
What about this tutorial? https://github.com/flashlight/flashlight/blob/master/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb Or you want to have streaming inference?

**Comment by gevorgyana** [comment]
Yes, streaming inference, please! That would be great. 

P.S.: I am still trying to read carefully through the mentioned tutorial, maybe I will find answers to my questions there.

Btw, here is a link to the full discussion, I am not the only one interested in streaming inference with Flashlight: https://github.com/flashlight/flashlight/discussions/601

Thank you!

**Comment by tlikhomanenko** [comment]
If you want online inference with conv models then it is here https://github.com/flashlight/wav2letter/wiki/Inference-Run-Examples (including tutorials). If this is still not what you are searching, can you formulate more concretely?

**Comment by gevorgyana** [comment]
@tlikhomanenko exactly what I wanted, thanks. I did not search the other https://github.com/flashlight/wav2letter/ repository.

**Comment by gevorgyana** [comment]
I still have a question: can I run inference based on real-time data that comes from a microphone? Is it possible to do something like polling on a .wav file? I have a microphone, the microphone records audio. I need that audio to be transcribed. That's my task. The tutorial you mentioned does not talk about accomplishing that. Thank you and I am sorry for reopening this one more time!

**Comment by tlikhomanenko** [comment]
What about this part https://github.com/flashlight/wav2letter/wiki/Inference-Run-Examples#Interactive-streaming-asr-example? If you want cpp file which doing recording of the audio (so online audio, not just taking final wav file as input) and then transcribing - you need to code this by yourself, but examples I sent should be enough to use in a way you need.

**Comment by gevorgyana** [comment]
Okay, clear for now, I am closing this. Thanks!

**Comment by pranavpawar3** [comment]
Hi @gevorgyana, I am trying to implement the same thing but have been facing issues with installing wave2letter inference which is needed for this -- https://github.com/flashlight/wav2letter/wiki/Inference-Run-Examples#Interactive-streaming-asr-example. Despite trying multiple times the wave2letter installation fails with the following error -- (I am following the installation instructions given here -https://github.com/flashlight/wav2letter/wiki/General-building-instructions and https://github.com/flashlight/wav2letter/wiki/Dependencies)

```
CMake Error at CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "flashlight" with
  any of the following names:

    flashlightConfig.cmake
    flashlight-config.cmake

  Add the installation prefix of "flashlight" to CMAKE_PREFIX_PATH or set
  "flashlight_DIR" to a directory containing one of the above files.  If
  "flashlight" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/content/wav2letter/build/CMakeFiles/CMakeOutput.log".

```

Can you please share if you have got this working? if yes, then how?

Thanks
