### ISSUE TITLE
[Your bug title]

### ISSUE THREAD

**Issue by georgekald79** [flashlight/flashlight#616]
### Bug Description
[A clear, concise description of the bug]

#### Reproduction Steps
[Steps to reproduce. Please include, if needed for your issue:
- Any configurations or custom setup
- Commands to run
- A trace of the error]

### Platform and Hardware
[Please list your operating system, [GPU] hardware, compiler, and other details if relevant]

#### Additional Context
[Add any additional information here]

**Comment by tlikhomanenko** [comment]
Closing as noo any bug description is given @georgekald79  please create the issue with necessary information.
