### ISSUE TITLE
python3 setup.py install stopped at [ 26%] Built target CUB

### ISSUE THREAD

**Issue by JeromeNi** [flashlight/flashlight#617]
### Question
I tried to install the python bindings but the script seems to have stopped when building target CUB. Below is the complete error log:
https://gist.github.com/JeromeNi/dbf266978a30f30258bf92952138d1d8

#### Additional Context
Before encountering this error, I did the following things to get around some other error messages:

1. I have to additionally add `set (CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -Xcompiler -mno-float128")` as a workaround for the gcc and CUDA version on the server I use.

2. I have to disable Intel MKL when building and let the script choose OpenBLAS instead.

3. I have to use cmake to generate `FFTW3LibraryDepends.cmake` for fftw-3.3.9 and put it into the corresponding `lib` folder.

Below is the related system information:
CUDA Version: 10.2
Python Version: 3.7.9
cmake: 3.20.2
gcc: 8.3.0
CPU: IBM Power9 (ppc64le)
Linux Version: 4.14.0-115.10.1.el7a.ppc64le

Thank you for the help!

**Comment by tlikhomanenko** [comment]
CUB will be downloaded automatically if it is not found. So it is not the issue in your case. Seems the problem that you change cmake cuda flags, it now cannot find the arch as it is empty https://gist.github.com/JeromeNi/dbf266978a30f30258bf92952138d1d8#file-gistfile1-txt-L118.

Can you try to build without your hacks for cuda flags? what is the problem then?
@jacobkahn could you correct me if I am totally wrong.

**Comment by JeromeNi** [comment]
Hello, without the cuda flag it will not progress beyond the nvcc check and throw `error: identifier "__ieee128" is undefined`. I applied the workaround mentioned in a Google search from here: https://github.com/LLNL/blt/issues/341

Below is the full error log without the hack for cuda flag:
https://gist.github.com/JeromeNi/bc6b03e9366fa28032c816d84d8f77c8

**Comment by JeromeNi** [comment]
I think I am able to build successfully by adding -DCMAKE_CUDA_ARCHITECTURES="70", which is the compute capability of the GPUs on the server. At least I could import multiple modules without issues; I will do more testing once I had the chance. Thanks for identifying the issue.

**Comment by webbp** [comment]
Caused by https://github.com/FFTW/fftw3/issues/130
