### ISSUE TITLE
Make failed with CPU BACKEND

### ISSUE THREAD

**Issue by akafen** [flashlight/flashlight#619]
#### Reproduction Steps
[Steps to reproduce. Please include, if needed for your issue:
cmake configuration:
> cmake .. -DCMAKE_BUILD_TYPE=Release -DFL_BACKEND=CPU -DKENLM_LIB=/path/kenlm_install -DKENLM_INCLUDE_DIRS=/path/kenlm_install -DDNNL_DIR=/path/oneDNN_install/lib/cmake/dnnl/ -DArrayFire_DIR=/path/arrayfire/share/ArrayFire/cmake/ -DKENLM_UTIL_LIB=/path/kenlm_install  -DKENLM_MODEL_HEADER=/path/kenlm_install/include/kenlm/lm

cmake log:

> -- The CXX compiler identification is GNU 8.3.0
> -- The C compiler identification is GNU 8.3.0
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Performing Test COMPILER_SUPPORTS_RDYNAMIC
> -- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
> -- -rdynamic supported.
> -- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) (Required is at least version "1.10.0")
> -- googletest not found - will download and build from source
> -- Will build flashlight libraries.
> -- MKL_THREADING = OMP
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of void*
> -- Check size of void* - done
> -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
> --   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
> --   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
> --   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
> --   Library gomp: -fopenmp
> --   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
> --   Library m: /usr/lib/x86_64-linux-gnu/libm.so
> --   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
> -- Looking for cblas_sgemm
> -- Looking for cblas_sgemm - found
> -- MKL library found
> -- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
> /home/liuyijiao/fftw/lib/cmake/fftw3
> -- FFTW found
> -- Found OpenMP_C: -fopenmp (found version "4.5")
> -- Found OpenMP_CXX: -fopenmp (found version "4.5")
> -- Found OpenMP: TRUE (found version "4.5")
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Looking for KenLM
> -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
> -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
> -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
> -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
> -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
> -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
> -- Found LibLZMA: /usr/include (found version "5.2.4")
> -- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
> -- Looking for BZ2_bzCompressInit
> -- Looking for BZ2_bzCompressInit - found
> -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
> -- Using kenlm library found in /home/liuyijiao/kenlm_install
> -- Using kenlm utils library found in /home/liuyijiao/kenlm_install
> -- kenlm model.hh found in /home/liuyijiao/kenlm_install/include/kenlm/lm
> -- Found kenlm: /home/liuyijiao/kenlm_install/include
> -- Found kenlm (include: /home/liuyijiao/kenlm_install/include, library: /home/liuyijiao/kenlm_install;/home/liuyijiao/kenlm_install;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)
> -- FL_BACKEND is not CUDA - forcing FL_LIBRARIES_USE_CUDA to OFF
> -- Will build flashlight core and extensions.
> -- Could NOT find cereal (missing: cereal_DIR)
> -- Could NOT find cereal (missing: cereal_INCLUDE_DIRS)
> -- Found cereal (include: )
> -- cereal NOT found. Will download from source
> -- Will build flashlight contrib assets.
> -- Could NOT find Gloo (missing: Gloo_DIR)
> -- Gloo not found - downloading and building from source
> -- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1")
> -- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1")
> -- Found MPI: TRUE (found version "3.1")
> -- MPI_VERSION found:  3.1
> -- MPI_CXX found
> -- MPI_CXX compile flags:
> -- MPI_CXX include path: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/usr/lib/x86_64-linux-gnu/openmpi/include
> -- MPI_CXX LINK flags path: -pthread
> -- MPI_CXX libraries: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
> -- MPI_C found
> -- MPI_C compile flags:
> -- MPI_C include path: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/usr/lib/x86_64-linux-gnu/openmpi/include
> -- MPI_C LINK flags path: -pthread
> -- MPI_C libraries: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
> -- ArrayFire found (include: /home/liuyijiao/arrayfire/include, library: ArrayFire::afcuda)
> -- Could NOT find stb (missing: stb_INCLUDE_DIRS)
> -- Could not find stb_image.h. Will download stb from github
> -- Configuring done
> WARNING: Target "fl-libraries" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "fl-libraries" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "flashlight" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "fl-libraries" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "fl-libraries" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "flashlight" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "PreEmphasisTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "CeplifterTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "DerivativesTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "DctTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "WindowingTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "MfccTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "StringTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "SpeechUtilsTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "ProducerConsumerQueueTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "SystemTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "DictionaryTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "DitherTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "TriFilterbankTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "TokenizerTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "ShapeTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "TensorBaseTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "ContribSerializationTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "ContribModuleTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "AllReduceTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "SerializationTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "HistogramTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "AutogradTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "ModuleTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "NNUtilsTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "LoggingTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "NNSerializationTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "DevicePtrTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "MeterTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "CachingMemoryManagerTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "OptimTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "MemoryFrameworkTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "DynamicBenchmarkTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "MemoryInitTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "DatasetTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "DatasetUtilsTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "LinearRegression" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "Xor" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "Mnist" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "RnnLm" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "RnnClassification" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "Classification" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "Benchmark" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "AdaptiveClassification" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "Perceptron" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "DistributedTraining" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "SequentialBuilderTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "DynamicScalerTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "ModelSerializationTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "ModulePluginTest" requests linking to directory "/home/liuyijiao/kenlm_install".  Targets may link only to libraries.  CMake is dropping the item.
> -- Generating done
> -- Build files have been written to: /home/liuyijiao/flashlight/build

Althought I install cereal and gloo , and I set them to the enviroment, but cmake couldn't find them
And then make -j8,log:

> Scanning dependencies of target stb
> Scanning dependencies of target gtest
> Scanning dependencies of target fl-libraries
> Scanning dependencies of target Gloo
> Scanning dependencies of target cereal
> [  0%] Creating directories for 'Gloo'
> [  0%] Creating directories for 'gtest'
> [  0%] Creating directories for 'cereal'
> [  0%] Creating directories for 'stb'
> [  0%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/set/Hungarian.cpp.o
> [  0%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ForceAlignmentCriterion.cpp.o
> [  0%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ConnectionistTemporalClassificationCriterion.cpp.o
> [  1%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/CriterionUtils.cpp.o
> [  2%] Performing download step (git clone) for 'Gloo'
> [  2%] Performing download step (git clone) for 'gtest'
> [  2%] Performing download step (git clone) for 'stb'
> [  2%] Performing download step (git clone) for 'cereal'
> Cloning into 'gtest'...
> Cloning into 'cereal'...
> Cloning into 'Gloo'...
> [  3%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/FullConnectionCriterion.cpp.o
> [  3%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ViterbiPath.cpp.o
> [  3%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Ceplifter.cpp.o
> [  4%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dct.cpp.o
> [  4%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Derivatives.cpp.o
> [  4%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dither.cpp.o
> [  5%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfcc.cpp.o
> [  5%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfsc.cpp.o
> [  6%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PowerSpectrum.cpp.o
> [  6%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PreEmphasis.cpp.o
> [  6%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/SpeechUtils.cpp.o
> [  7%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/TriFilterbank.cpp.o
> [  7%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Windowing.cpp.o
> [  7%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/String.cpp.o
> [  8%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/System.cpp.o
> [  8%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ConvLM.cpp.o
> [  8%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ZeroLM.cpp.o
> [  9%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/KenLM.cpp.o
> [  9%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconDecoder.cpp.o
> [ 10%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconFreeDecoder.cpp.o
> [ 10%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconSeq2SeqDecoder.cpp.o
> [ 10%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconFreeSeq2SeqDecoder.cpp.o
> [ 11%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/Trie.cpp.o
> [ 11%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/Utils.cpp.o
> [ 11%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/dictionary/Dictionary.cpp.o
> [ 12%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/dictionary/Utils.cpp.o
> [ 12%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/tokenizer/PartialFileReader.cpp.o
> [ 12%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/tokenizer/Tokenizer.cpp.o
> [ 13%] Linking CXX static library libfl-libraries.a
> [ 13%] Built target fl-libraries
> fatal: unable to access 'https://github.com/facebookincubator/gloo.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
> fatal: unable to access 'https://github.com/USCiLab/cereal.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
> Cloning into 'cereal'...
> Cloning into 'Gloo'...
> fatal: unable to access 'https://github.com/google/googletest.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
> Cloning into 'gtest'...
> -- stb download command succeeded.  See also /home/liuyijiao/flashlight/build/stb/src/stb-stamp/stb-download-*.log
> [ 14%] No patch step for 'stb'
> [ 14%] Performing update step for 'stb'
> [ 14%] No configure step for 'stb'
> [ 15%] No build step for 'stb'
> [ 16%] No install step for 'stb'
> [ 16%] Completed 'stb'
> [ 16%] Built target stb
> fatal: unable to access 'https://github.com/USCiLab/cereal.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
> Cloning into 'cereal'...
> fatal: unable to access 'https://github.com/google/googletest.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
> Cloning into 'gtest'...
> fatal: unable to access 'https://github.com/facebookincubator/gloo.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
> Cloning into 'Gloo'...
> -- Had to git clone more than once:
>           3 times.
> Note: checking out '703bd9caab50b139428cea1aaff9974ebee5742e'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at 703bd9ca Googletest export
> [ 16%] No patch step for 'gtest'
> [ 17%] Performing update step for 'gtest'
> [ 18%] Performing configure step for 'gtest'
> loading initial cache file /home/liuyijiao/flashlight/build/googletest/tmp/gtest-cache-Release.cmake
> -- The C compiler identification is GNU 8.3.0
> -- The CXX compiler identification is GNU 8.3.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found PythonInterp: /usr/bin/python (found version "2.7.16")
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/liuyijiao/flashlight/build/googletest/src/gtest
> [ 18%] Performing build step for 'gtest'
> make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> Scanning dependencies of target gtest
> [ 12%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
> [ 25%] Linking CXX static library ../lib/libgtest.a
> [ 25%] Built target gtest
> Scanning dependencies of target gmock
> [ 37%] Building CXX object googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
> [ 50%] Linking CXX static library ../lib/libgmock.a
> [ 50%] Built target gmock
> Scanning dependencies of target gmock_main
> [ 62%] Building CXX object googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
> [ 75%] Linking CXX static library ../lib/libgmock_main.a
> [ 75%] Built target gmock_main
> Scanning dependencies of target gtest_main
> [ 87%] Building CXX object googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
> [100%] Linking CXX static library ../lib/libgtest_main.a
> [100%] Built target gtest_main
> [ 19%] No install step for 'gtest'
> [ 19%] Completed 'gtest'
> [ 19%] Built target gtest
> Scanning dependencies of target PreEmphasisTest
> Scanning dependencies of target DerivativesTest
> Scanning dependencies of target WindowingTest
> Scanning dependencies of target CeplifterTest
> Scanning dependencies of target MfccTest
> make[2]: *** No rule to make target '/home/liuyijiao/fftw-3.3.9/build/libfftw3.so.3', needed by 'flashlight/lib/test/PreEmphasisTest'.  Stop.
> make[2]: *** Waiting for unfinished jobs....
> Scanning dependencies of target DctTest
> make[2]: *** No rule to make target '/home/liuyijiao/fftw-3.3.9/build/libfftw3.so.3', needed by 'flashlight/lib/test/DerivativesTest'.  Stop.
> make[2]: *** Waiting for unfinished jobs....
> make[2]: *** No rule to make target '/home/liuyijiao/fftw-3.3.9/build/libfftw3.so.3', needed by 'flashlight/lib/test/WindowingTest'.  Stop.
> make[2]: *** Waiting for unfinished jobs....
> make[2]: *** No rule to make target '/home/liuyijiao/fftw-3.3.9/build/libfftw3.so.3', needed by 'flashlight/lib/test/MfccTest'.  Stop.
> make[2]: *** Waiting for unfinished jobs....
> [ 19%] Building CXX object flashlight/lib/test/CMakeFiles/PreEmphasisTest.dir/audio/feature/PreEmphasisTest.cpp.o
> make[2]: *** No rule to make target '/home/liuyijiao/fftw-3.3.9/build/libfftw3.so.3', needed by 'flashlight/lib/test/CeplifterTest'.  Stop.
> make[2]: *** Waiting for unfinished jobs....
> make[2]: *** No rule to make target '/home/liuyijiao/fftw-3.3.9/build/libfftw3.so.3', needed by 'flashlight/lib/test/DctTest'.  Stop.
> make[2]: *** Waiting for unfinished jobs....
> [ 19%] Building CXX object flashlight/lib/test/CMakeFiles/CeplifterTest.dir/audio/feature/CeplifterTest.cpp.o
> [ 20%] Building CXX object flashlight/lib/test/CMakeFiles/DerivativesTest.dir/audio/feature/DerivativesTest.cpp.o
> [ 21%] Building CXX object flashlight/lib/test/CMakeFiles/WindowingTest.dir/audio/feature/WindowingTest.cpp.o
> [ 22%] Building CXX object flashlight/lib/test/CMakeFiles/DctTest.dir/audio/feature/DctTest.cpp.o
> [ 22%] Building CXX object flashlight/lib/test/CMakeFiles/MfccTest.dir/audio/feature/MfccTest.cpp.o
> make[1]: *** [CMakeFiles/Makefile2:1239: flashlight/lib/test/CMakeFiles/PreEmphasisTest.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:1277: flashlight/lib/test/CMakeFiles/CeplifterTest.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:1353: flashlight/lib/test/CMakeFiles/DctTest.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:1315: flashlight/lib/test/CMakeFiles/DerivativesTest.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:1391: flashlight/lib/test/CMakeFiles/WindowingTest.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:1429: flashlight/lib/test/CMakeFiles/MfccTest.dir/all] Error 2
> fatal: unable to access 'https://github.com/USCiLab/cereal.git/': Error in the HTTP2 framing layer
> -- Had to git clone more than once:
>           3 times.
> CMake Error at /home/liuyijiao/flashlight/build/cereal/tmp/cereal-gitclone.cmake:66 (message):
>   Failed to clone repository: 'https://github.com/USCiLab/cereal.git'
> 
> 
> make[2]: *** [CMakeFiles/cereal.dir/build.make:90: cereal/src/cereal-stamp/cereal-download] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1083: CMakeFiles/cereal.dir/all] Error 2
> fatal: unable to access 'https://github.com/facebookincubator/gloo.git/': Error in the HTTP2 framing layer
> -- Had to git clone more than once:
>           3 times.
> CMake Error at /home/liuyijiao/flashlight/build/gloo/tmp/Gloo-gitclone.cmake:66 (message):
>   Failed to clone repository: 'https://github.com/facebookincubator/gloo.git'
> 
> 
> make[2]: *** [CMakeFiles/Gloo.dir/build.make:90: gloo/src/Gloo-stamp/Gloo-download] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1120: CMakeFiles/Gloo.dir/all] Error 2
> make: *** [Makefile:141: all] Error 2

### Platform and Hardware
[Please list your operating system, [GPU] hardware, compiler, and other details if relevant]
uname - a:
> Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

g++ -v:

> Using built-in specs.
> COLLECT_GCC=g++
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
> OFFLOAD_TARGET_NAMES=nvptx-none
> OFFLOAD_TARGET_DEFAULT=1
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by tlikhomanenko** [comment]
did you install https://github.com/flashlight/flashlight/blob/master/.docker/Dockerfile-CUDA-Base#L45? Seems something bogus with your versions, it found  `/home/liuyijiao/fftw/lib/cmake/fftw3` but then asks for `/home/liuyijiao/fftw-3.3.9/build/libfftw3.so.3`. So please recheck your fftw3 installation.

**Comment by akafen** [comment]
> did you install https://github.com/flashlight/flashlight/blob/master/.docker/Dockerfile-CUDA-Base#L45? Seems something bogus with your versions, it found `/home/liuyijiao/fftw/lib/cmake/fftw3` but then asks for `/home/liuyijiao/fftw-3.3.9/build/libfftw3.so.3`. So please recheck your fftw3 installation.

@tlikhomanenko I install fftw3 from source, `/home/liuyijiao/fftw-3.3.9/build/libfftw3.so.3` is my fftw3 source location, `/home/liuyijiao/fftw`  is my fftw3 install location, I think my fftw3 installation  is ok?

**Comment by akafen** [comment]
@tlikhomanenko  I found the problem. Since I used source code to install fftw3, but after installation, fftw3 would miss FFTW3LibraryDepends.cmake in /path/fftw3_installation/lib/cmake/fftw3 ,so I copy FFTW3LibraryDepends.cmake in source code to installation,but I didn't change some code in FFTW3LibraryDepends.cmake which direct to /home/liuyijiao/fftw-3.3.9/build/libfftw3.so.3. That is the problem.Thanks

**Comment by webbp** [comment]
Caused by https://github.com/FFTW/fftw3/issues/130
