### ISSUE TITLE
 Could not find a package configuration file provided by "DNNL" with the name dnnl-config.cmake while using docker with cpu-backend

### ISSUE THREAD

**Issue by sahilg06** [flashlight/flashlight#621]
### Question
I am using flashlight docker with CPU-backend(in Macbook air M1 chip). I tried to run a sample example  but the following error appeared
```
CMake Error at /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindDNNL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DNNL", but
  CMake did not find one.
  Could not find a package configuration file provided by "DNNL" with any of
  the following names:

    DNNLConfig.cmake
    dnnl-config.cmake

  Add the installation prefix of "DNNL" to CMAKE_PREFIX_PATH or set
  "DNNL_DIR" to a directory containing one of the above files.  If "DNNL"
  provides a separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /opt/flashlight/share/flashlight/cmake/flashlightConfig.cmake:46 (find_dependency)
  CMakeLists.txt:7 (find_package)
```

#### Additional Context
I also tried to set the environment  variable 
`cmake .. -DCMAKE_BUILD_TYPE=Release -DNNL_DIR=/opt/onednn/lib/cmake/dnnl`
But same error appeared. Please help.

**Comment by tlikhomanenko** [comment]
Could you follow installation steps as in docker image build here https://github.com/flashlight/flashlight/blob/master/.docker/Dockerfile-CPU#L10-L27?

**Comment by saswatpp** [comment]
I think you have a typo @sahilg06 . Your command should be : 
`cmake .. -DCMAKE_BUILD_TYPE=Release -DDNNL_DIR=/opt/onednn/lib/cmake/dnnl`

I.e. -DDNNL_DIR and not -DNNL-DIR

**Comment by sahilg06** [comment]
Thanks, @saswatpp @tlikhomanenko. @saswatpp, You are right, it was a typo. So closing this issue
