### ISSUE TITLE
Performance Bug While Training ResNet using Flashlight

### ISSUE THREAD

**Issue by mtmd** [flashlight/flashlight#630]
### Bug Description
The performance of flashlight when training ResNet is lower than that of PyTorch for training the same network. 

#### Reproduction Steps
To reproduce, simply run
```
bin/imgclass/fl_img_imagenet_resnet34 \
--data_dir=/path/to/your/ImageNet/folder \
--distributed_enable=false \
--exp_checkpoint_path=/tmp/test \
--logtostderr \
--fl_amp_use_mixed_precision=false \
--data_batch_size=128
```
### Platform and Hardware
NVIDIA V100 - 16GB and NVIDIA V100 - 32GB. The bug is expected to be reproducible on other GPUs as well. However, it is not confirmed yet.

**Comment by jacobkahn** [comment]
See PR.
