### ISSUE TITLE
Building flashlight for CPU backend can't find libsycl.so

### ISSUE THREAD

**Issue by abhisina** [flashlight/flashlight#632]
### Question
I am trying to build flashlight from source by following the installation description for CPU back-end on Ubuntu 20.04.2. I have been able to resolve other build issues by referring internet elsewhere. However, I continue to get the below error and am unable to find any solution.

> /usr/bin/ld: cannot find -lsycl

#### Additional Context
- I am using g++-9
- The build command is as below:
> cmake .. -DCMAKE_BUILD_TYPE=Release -DFL_BACKEND=CPU -DDNNL_DIR=/opt/intel/oneapi/dnnl/latest/lib/cmake/dnnl -DTBB_DIR=/opt/intel/oneapi/tbb/latest/lib/cmake/tbb -DFL_LIBRARIES_USE_KENLM=FALSE -DFL_BUILD_TESTS=FALSE -DFL_BUILD_APP_ASR=TRUE  
- I do see that the library `libsycl.so` is available in `/opt/intel/oneapi/compiler/latest/linux/lib` but not sure how to pick that library up, exporting `LD_LIBRARY_PATH` does not help
- Additionally I see `libOpenCL.so` as well in the same path but does not seem to getting referenced from here presently
  - The error regarding OpenCL went away after running the following command:
  - `sudo apt install ocl-icd-opencl-dev`
  - Tried to use the bundled compiler at `/opt/intel/oneapi/compiler/latest/linux/bin/clang++` but that compiler seems very old

**Comment by tlikhomanenko** [comment]
cc @jacobkahn @xuqiantong @vineelpratap
