### ISSUE TITLE
MKL library not found

### ISSUE THREAD

**Issue by sahilg06** [flashlight/flashlight#640]
### Question
Cmake is not able to find MKL while installing flashlight(building other dependencies using vcpkg and building ArrayFire from the source). Using Macbook Air (M1 chip).
```
cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DFL_BACKEND=CPU \
    -DCMAKE_TOOLCHAIN_FILE=/Users/sahilgoyal/vcpkg/scripts/buildsystems/vcpkg.cmake \
    -DArrayFire_DIR=/Users/sahilgoyal/arrayfire/build/cmake/install/ArrayFireConfig.cmake \
    -DFL_BUILD_DISTRIBUTED=OFF 
    
make -j2 
make install -j2

```

Attaching output 
```
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- The C compiler identification is AppleClang 12.0.0.12000032
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- -rdynamic supported.
-- Found GTest: /Users/sahilgoyal/vcpkg/installed/arm64-osx/share/GTest/GTestConfig.cmake (found suitable version "1.10.0", minimum required is "1.10.0")
-- gtest found: (include: , lib: GTest::gtest;GTest::gtest_main
-- Found gtest and gmock on system.
-- Will build flashlight libraries.
-- MKL_THREADING = OMP
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_lp64.dylib
--   Library mkl_intel_thread: /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_thread.dylib
--   Library mkl_core: /opt/intel/oneapi/mkl/latest/lib/libmkl_core.dylib
--   Library iomp5: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - guide - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_lp64.dylib
--   Library mkl_intel_thread: /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_thread.dylib
--   Library mkl_core: /opt/intel/oneapi/mkl/latest/lib/libmkl_core.dylib
--   Library guide: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - guide - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_lp64.dylib
--   Library mkl_intel_thread: /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_thread.dylib
--   Library mkl_core: /opt/intel/oneapi/mkl/latest/lib/libmkl_core.dylib
--   Library pthread: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libpthread.tbd
--   Library m: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libm.tbd
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_sequential - mkl_core - m]
--   Library mkl_intel_lp64: /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_lp64.dylib
--   Library mkl_sequential: /opt/intel/oneapi/mkl/latest/lib/libmkl_sequential.dylib
--   Library mkl_core: /opt/intel/oneapi/mkl/latest/lib/libmkl_core.dylib
--   Library m: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libm.tbd
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - not found
-- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_lp64.dylib
--   Library mkl_core: /opt/intel/oneapi/mkl/latest/lib/libmkl_core.dylib
--   Library iomp5: not found
-- Checking for [mkl_intel - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_core - guide - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_lp64.dylib
--   Library mkl_core: /opt/intel/oneapi/mkl/latest/lib/libmkl_core.dylib
--   Library guide: not found
-- Checking for [mkl_intel - mkl_core - guide - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_core - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_lp64.dylib
--   Library mkl_core: /opt/intel/oneapi/mkl/latest/lib/libmkl_core.dylib
--   Library pthread: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libpthread.tbd
--   Library m: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libm.tbd
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - not found
-- Checking for [mkl_intel - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
CMake Error at cmake/FindMKL.cmake:400 (MESSAGE):
  MKL library not found.  Please specify library location by appending the
  root directory of the MKL installation to the environment variable
  CMAKE_PREFIX_PATH.
Call Stack (most recent call first):
  /Users/sahilgoyal/vcpkg/scripts/buildsystems/vcpkg.cmake:764 (_find_package)
  flashlight/lib/audio/feature/CMakeLists.txt:6 (find_package)
  flashlight/lib/audio/CMakeLists.txt:6 (include)
  flashlight/lib/CMakeLists.txt:31 (include)
  CMakeLists.txt:133 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/sahilgoyal/flashlight/build/CMakeFiles/CMakeOutput.log".
See also "/Users/sahilgoyal/flashlight/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
```

Error-log file(Here it seems a Mac related issue)
[CMakeError.log](https://github.com/flashlight/flashlight/files/6660660/CMakeError.log)

#### Additional Context
Tried following
```
export CMAKE_PREFIX_PATH="/opt/intel/oneapi/mkl/latest:$PATH"
export MKLROOT=/opt/intel/oneapi/mkl/latest
export CMAKE_LIBRARY_PATH='/opt/intel/oneapi/mkl/latest/lib'
```
Followed this to install intel-mkl 
https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit/download.html?operatingsystem=mac&distributions=webdownload&options=online

Please Help!

**Comment by tlikhomanenko** [comment]
We often specify path to mkl as `export MKLROOT=/opt/intel/mkl`, maybe you should try specify it as `export MKLROOT=/opt/intel/oneapi/mkl` or as we do. Could you confirm that both export doesn't work?

**Comment by sahilg06** [comment]
@tlikhomanenko Actually, when I didn't try any export the error was as follow:

```
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - guide - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - guide - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_sequential - mkl_core - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_core - guide - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_core - guide - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_core - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
CMake Error at cmake/FindMKL.cmake:400 (MESSAGE):
  MKL library not found.  Please specify library location by appending the
  root directory of the MKL installation to the environment variable
  CMAKE_PREFIX_PATH.
Call Stack (most recent call first):
  /Users/sahilgoyal/vcpkg/scripts/buildsystems/vcpkg.cmake:764 (_find_package)
  flashlight/lib/audio/feature/CMakeLists.txt:6 (find_package)
  flashlight/lib/audio/CMakeLists.txt:6 (include)
  flashlight/lib/CMakeLists.txt:31 (include)
  CMakeLists.txt:133 (include)
```

 And when I tried this export, still the error was the same
```
export MKLROOT=/opt/intel/oneapi/mkl
```

And When I tried this export, the error changes to the one that I posted initially.
```
export MKLROOT=/opt/intel/oneapi/mkl/latest
```

When I go to the following path, there is no such library there (iomp5, guide, etc)
```
/opt/intel/oneapi/mkl/latest/lib
```
<img width="1373" alt="Screenshot 2021-06-17 at 11 43 19" src="https://user-images.githubusercontent.com/59660566/122341564-3d2bf380-cf61-11eb-8e63-5a0b50ef9a83.png">

**Comment by tlikhomanenko** [comment]
How did you installed the mkl?

**Comment by sahilg06** [comment]
I installed mkl by following this https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit/download.html?operatingsystem=mac&distributions=webdownload&options=online 

and later linked it with vcpkg using
```
./vcpkg/vcpkg install intel-mkl
```

**Comment by tlikhomanenko** [comment]
@jacobkahn any idea on mkl?

**Comment by sahilg06** [comment]
Moreover when I do ```./vcpkg list``` it shows  ```2020.0.0``` version

<img width="947" alt="Screenshot 2021-06-17 at 12 13 38" src="https://user-images.githubusercontent.com/59660566/122345516-90a04080-cf65-11eb-82b7-38d53d11cc49.png">

and where I installed the intel-mkl it shows these two in /opt/intel/oneapi/mkl folder 
```latest``` and ```2021.2.0```

**Comment by alkazap** [comment]
Maybe try uninstalling vcpkg MKL and install it with a local installer https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit/download.html
This worked for me
Note: if you are working on a remote server, the installation script by default opens a GUI window, for command line installation use  `sudo sh ./l_[Toolkit Name]Kit_[version].sh -a --cli` 
https://software.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-linux/top/installation/install-with-command-line.html

**Comment by sahilg06** [comment]
Hi @alkazap, I installed it in a similar way only as I mentioned in https://github.com/flashlight/flashlight/issues/640#issuecomment-862968845 but later just linked it to vcpkg.

**Comment by sahilg06** [comment]
I don't know why it involves too much headache to build the flashlight library. I tried various methods (such as building with vcpkg which gave me some ArrayFire error (mkl-threading library missing), then I tried building ArrayFire from source and all other dependencies via vcpkg then this error appeared)   but was successful only via docker(CPU) which is too slow to use.
I also tried to use docker(CUDA) but `nvidia-smi ` was not working there, means CUDA is not installed in docker itself.

**Comment by alkazap** [comment]
@sahilg06 I did not have to link it to vcpkg to compile, I just used `. /opt/intel/oneapi/setvars.sh` to set environment variables and it worked (I did have to fix `/vcpkg/ports/flashlight-cuda/portfile.cmake.bk` tho)

**Comment by Jibril2** [comment]
I've been trying for 3 days now to install it and keep going in circles with dependency issues. Worst installation I've ever dealt with T_T

**Comment by tlikhomanenko** [comment]
@sahilg06 

Cuda docker is using the cuda driver on your machine, so if you don't have gpus or driver it will not work. You can simply follow nvidia-docker to be sure nvidia-smi is working for you and then use our docker.

Also to simplify installation you can follow exact commands in dockerfiles to install everything from source with all deps, but this was tested for clean ubuntu, thus if you have some deps already installed you need to figure out what/how to linkk properly. 


@Jibril2 could you be more specific what is wrong for you? Simplest case is to use docker image then.

**Comment by dreamgonfly** [comment]
If anyone is still facing the same issue...

I solved this MKL library not found issue. For some reason Flashlight doesn't recognize MKL library installed via intel's official website (which installs one-api). I solved it by installing MKL library via a specific apt package. I'll share my solution below.

```
cd /tmp && wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
    apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
    sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list' && \
    apt-get update && \
    apt install intel-mkl-64bit-2020.4-912
```

This installs MKL library under `/opt/intel/mkl`. (Note that if you install MKL library following the official instructions it's installed under `/opt/intel/oneapi/mkl`) With this installation, Flashlight successfully finds the MKL library. You don't even need to specify MKLROOT environment variable. (Of course you can do `export MKLROOT="/opt/intel/mkl"` if you want to.)

I adopted this solution from the official dockerfile.

**Comment by kommander** [comment]
For anyone still running into this on Win10:
- If using PowerShell, ensure to set env variable with `$env:MKLROOT="path/to/mkl/latest"`
- Since some MKL version (at least 2022.0.2), the lib version folder is called `intel64` NOT `intel64_win`
	- Remove lines [~110-116 in `cmake/FindMKL.cmake`](https://github.com/flashlight/flashlight/blob/main/cmake/FindMKL.cmake#L110-L116), where it overrides with `_win` postfix

**Comment by mqnc** [comment]
`sudo ln -s /opt/intel/oneapi/mkl/latest /opt/intel/mkl`

did the trick for me so I could advance to the next problem
