### ISSUE TITLE
Using python bindings: No module named 'flashlight.lib.text.flashlight_lib_text_decoder'

### ISSUE THREAD

**Issue by akafen** [flashlight/flashlight#663]
### Question
After python3 setup.py install succecsfully, I run ipython : "import flashlight.lib.text.decoder", but error happend:No module named 'flashlight.lib.text.flashlight_lib_text_decoder', I don't know how to fix

**Comment by tlikhomanenko** [comment]
Can you run python tests and check if they work after installation?

**Comment by akafen** [comment]
@tlikhomanenko 
Fix the error.Thanks

**Comment by Toan-it-mta** [comment]
@akafen 

How do you fix that ?? 

--Thanks--

**Comment by akafen** [comment]
@Toan-it-mta 
Linux: 
`cp build/lib.linux-x86_64-3.7/flashlight/lib/text/flashlight_lib_text_d* flashlight/lib/text/`

**Comment by Toan-it-mta** [comment]
i don't have this file 
>build/lib.linux-x86_64-3.7/flashlight/lib/text/flashlight_lib_text_d

**Comment by akafen** [comment]
@Toan-it-mta 
it is in flashlight/bindings/python/build/lib.linux-x86_64-3.7/flashlight/lib/text ,tow files:
```
flashlight_lib_text_decoder.cpython-37m-x86_64-linux-gnu.so
flashlight_lib_text_dictionary.cpython-37m-x86_64-linux-gnu.so
```
Filename may be different due to your system and python version. Directory name lib.linux-x86_64-3.7 also may be different. You just need to copy them to  flashlight/bindings/python/flashlight/lib/text/

**Comment by Toan-it-mta** [comment]
![image](https://user-images.githubusercontent.com/44705392/127630471-260ed066-9dd4-4f20-b836-b040fd9b968b.png)

THanks. But, looks like there are not 2 files in my directory as you mentioned.

Did you follow any instructions?

**Comment by akafen** [comment]
Emmm, it seems you have other problem that I don't hvae

**Comment by Toan-it-mta** [comment]
> @Toan-it-mta
> Emmm, it seems you have other problem that I don't hvae

Again, did you follow any instructions to install the 'Flashlight and  flashlight-binding'?

thank you very much

**Comment by tlikhomanenko** [comment]
> @Toan-it-mta
> Linux:
> `cp build/lib.linux-x86_64-3.7/flashlight/lib/text/flashlight_lib_text_d* flashlight/lib/text/`

This should be done automatically during installation. Not sure why you do this manually.

@Toan-it-mta  what the problem do you have? Can you post the output of your installation?
