### ISSUE TITLE
[Error when importing flashlight.lib.text.decoder] ImportError: /home/liuyijiao/arrayfire/lib64/libmkl_intel_lp64.so: undefined symbol: mkl_blas_mkl_cgemm_direct_jit

### ISSUE THREAD

**Issue by akafen** [flashlight/flashlight#665]
### Question
I have successfully installed flashlight according to [these steps](https://github.com/flashlight/flashlight). I have successfully installed python bindings according to these [steps.](https://github.com/flashlight/flashlight/tree/master/bindings/python)

> running install
> running bdist_egg
> running egg_info
> writing flashlight.egg-info/PKG-INFO
> writing dependency_links to flashlight.egg-info/dependency_links.txt
> writing top-level names to flashlight.egg-info/top_level.txt
> package init file 'flashlight/__init__.py' not found (or not a regular file)
> package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
> package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
> package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
> reading manifest file 'flashlight.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'flashlight.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> ------------debug /home/liuyijiao/flashlight/bindings/python/build/lib.linux-x86_64-3.7/flashlight/lib/audio/feature.cpython-37m-x86_64-linux-gnu.so
> -- -rdynamic supported.
> -- Will build flashlight libraries.
> libraries criterions are not implemented for non-CUDA backends
> -- MKL_THREADING = OMP
> -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
> --   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
> --   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
> --   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
> --   Library gomp: -fopenmp
> --   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
> --   Library m: /usr/lib/x86_64-linux-gnu/libm.so
> --   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
> -- MKL library found
> -- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
> /home/liuyijiao/fftw/lib/cmake/fftw3
> -- FFTW found
> -- Found OpenMP_C: -fopenmp
> -- Found OpenMP_CXX: -fopenmp
> -- Found OpenMP: TRUE
> -- Looking for KenLM
> -- Using kenlm library found in /home/liuyijiao/kenlm_install/lib/libkenlm.a
> -- Using kenlm utils library found in /home/liuyijiao/kenlm_install/lib/libkenlm_util.a
> -- kenlm model.hh found in /home/liuyijiao/kenlm_install/include/kenlm/lm
> -- Found kenlm: /home/liuyijiao/kenlm_install/include
> -- Found kenlm (include: /home/liuyijiao/kenlm_install/include, library: /home/liuyijiao/kenlm_install/lib/libkenlm.a;/home/liuyijiao/kenlm_install/lib/libkenlm_util.a;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)
> -- FL_BACKEND is not CUDA - forcing FL_LIBRARIES_USE_CUDA to OFF
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/liuyijiao/flashlight/bindings/python/build/temp.linux-x86_64-3.7
> Scanning dependencies of target fl-libraries
> Scanning dependencies of target pybind11
> [  2%] Creating directories for 'pybind11'
> [  4%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/set/Hungarian.cpp.o
> [  6%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/CriterionUtils.cpp.o
> [  8%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ForceAlignmentCriterion.cpp.o
> [ 10%] Performing download step (git clone) for 'pybind11'
> Cloning into 'pybind11'...
> [ 12%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ConnectionistTemporalClassificationCriterion.cpp.o
> [ 14%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/FullConnectionCriterion.cpp.o
> [ 16%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ViterbiPath.cpp.o
> [ 18%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Ceplifter.cpp.o
> [ 20%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dct.cpp.o
> [ 22%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Derivatives.cpp.o
> [ 24%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dither.cpp.o
> [ 26%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfcc.cpp.o
> [ 28%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfsc.cpp.o
> [ 30%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PowerSpectrum.cpp.o
> [ 32%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PreEmphasis.cpp.o
> [ 34%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/SpeechUtils.cpp.o
> [ 36%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/TriFilterbank.cpp.o
> [ 38%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Windowing.cpp.o
> [ 40%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/String.cpp.o
> [ 42%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/System.cpp.o
> [ 44%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ConvLM.cpp.o
> [ 46%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ZeroLM.cpp.o
> [ 48%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/KenLM.cpp.o
> [ 51%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconDecoder.cpp.o
> [ 53%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconFreeDecoder.cpp.o
> [ 55%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconSeq2SeqDecoder.cpp.o
> [ 57%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconFreeSeq2SeqDecoder.cpp.o
> [ 59%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/Trie.cpp.o
> [ 61%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/Utils.cpp.o
> [ 63%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/dictionary/Dictionary.cpp.o
> [ 65%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/dictionary/Utils.cpp.o
> [ 67%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/tokenizer/PartialFileReader.cpp.o
> [ 69%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/tokenizer/Tokenizer.cpp.o
> [ 71%] Linking CXX shared library ../lib.linux-x86_64-3.7/libfl-libraries.so
> [ 71%] Built target fl-libraries
> fatal: unable to access 'https://github.com/pybind/pybind11.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
> Cloning into 'pybind11'...
> -- Had to git clone more than once:
>           2 times.
> Note: checking out '9a19306fbf30642ca331d0ec88e7da54a96860f9'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at 9a19306 bump version to 2.2.4
> Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'tools/clang'
> Cloning into '/home/liuyijiao/flashlight/bindings/python/build/temp.linux-x86_64-3.7/pybind11/src/pybind11/tools/clang'...
> Submodule path 'tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
> [ 73%] Performing update step for 'pybind11'
> [ 75%] No patch step for 'pybind11'
> [ 77%] No configure step for 'pybind11'
> [ 79%] No build step for 'pybind11'
> [ 81%] No install step for 'pybind11'
> [ 83%] Completed 'pybind11'
> [ 83%] Built target pybind11
> Scanning dependencies of target flashlight_lib_text_dictionary
> Scanning dependencies of target flashlight_lib_text_decoder
> Scanning dependencies of target flashlight_lib_audio_feature
> Scanning dependencies of target flashlight_lib_sequence_criterion
> [ 85%] Building CXX object CMakeFiles/flashlight_lib_text_decoder.dir/bindings/python/flashlight/lib/text/_decoder.cpp.o
> [ 87%] Building CXX object CMakeFiles/flashlight_lib_text_dictionary.dir/bindings/python/flashlight/lib/text/_dictionary.cpp.o
> [ 89%] Building CXX object CMakeFiles/flashlight_lib_sequence_criterion.dir/bindings/python/flashlight/lib/sequence/_criterion.cpp.o
> [ 91%] Building CXX object CMakeFiles/flashlight_lib_audio_feature.dir/bindings/python/flashlight/lib/audio/_feature.cpp.o
> [ 93%] Linking CXX shared module ../lib.linux-x86_64-3.7/flashlight/lib/text/flashlight_lib_text_dictionary.cpython-37m-x86_64-linux-gnu.so
> [ 95%] Linking CXX shared module ../lib.linux-x86_64-3.7/flashlight/lib/sequence/flashlight_lib_sequence_criterion.cpython-37m-x86_64-linux-gnu.so
> [ 97%] Linking CXX shared module ../lib.linux-x86_64-3.7/flashlight/lib/audio/flashlight_lib_audio_feature.cpython-37m-x86_64-linux-gnu.so
> [ 97%] Built target flashlight_lib_text_dictionary
> [ 97%] Built target flashlight_lib_sequence_criterion
> [100%] Linking CXX shared module ../lib.linux-x86_64-3.7/flashlight/lib/text/flashlight_lib_text_decoder.cpython-37m-x86_64-linux-gnu.so
> [100%] Built target flashlight_lib_audio_feature
> [100%] Built target flashlight_lib_text_decoder
> ------------debug /home/liuyijiao/flashlight/bindings/python/build/lib.linux-x86_64-3.7/flashlight/lib/sequence/criterion.cpython-37m-x86_64-linux-gnu.so
> -- -rdynamic supported.
> -- Will build flashlight libraries.
> libraries criterions are not implemented for non-CUDA backends
> -- MKL_THREADING = OMP
> -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
> --   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
> --   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
> --   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
> --   Library gomp: -fopenmp
> --   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
> --   Library m: /usr/lib/x86_64-linux-gnu/libm.so
> --   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
> -- MKL library found
> -- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
> /home/liuyijiao/fftw/lib/cmake/fftw3
> -- FFTW found
> -- Looking for KenLM
> -- Using kenlm library found in /home/liuyijiao/kenlm_install/lib/libkenlm.a
> -- Using kenlm utils library found in /home/liuyijiao/kenlm_install/lib/libkenlm_util.a
> -- kenlm model.hh found in /home/liuyijiao/kenlm_install/include/kenlm/lm
> -- Found kenlm (include: /home/liuyijiao/kenlm_install/include, library: /home/liuyijiao/kenlm_install/lib/libkenlm.a;/home/liuyijiao/kenlm_install/lib/libkenlm_util.a;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)
> -- FL_BACKEND is not CUDA - forcing FL_LIBRARIES_USE_CUDA to OFF
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/liuyijiao/flashlight/bindings/python/build/temp.linux-x86_64-3.7
> [  2%] Performing update step for 'pybind11'
> [ 69%] Built target fl-libraries
> [ 71%] No configure step for 'pybind11'
> [ 73%] No build step for 'pybind11'
> [ 75%] No install step for 'pybind11'
> [ 77%] Completed 'pybind11'
> [ 83%] Built target pybind11
> [ 91%] Built target flashlight_lib_text_decoder
> [ 91%] Built target flashlight_lib_text_dictionary
> [ 95%] Built target flashlight_lib_audio_feature
> [100%] Built target flashlight_lib_sequence_criterion
> ------------debug /home/liuyijiao/flashlight/bindings/python/build/lib.linux-x86_64-3.7/flashlight/lib/text/decoder.cpython-37m-x86_64-linux-gnu.so
> -- -rdynamic supported.
> -- Will build flashlight libraries.
> libraries criterions are not implemented for non-CUDA backends
> -- MKL_THREADING = OMP
> -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
> --   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
> --   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
> --   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
> --   Library gomp: -fopenmp
> --   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
> --   Library m: /usr/lib/x86_64-linux-gnu/libm.so
> --   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
> -- MKL library found
> -- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
> /home/liuyijiao/fftw/lib/cmake/fftw3
> -- FFTW found
> -- Looking for KenLM
> -- Using kenlm library found in /home/liuyijiao/kenlm_install/lib/libkenlm.a
> -- Using kenlm utils library found in /home/liuyijiao/kenlm_install/lib/libkenlm_util.a
> -- kenlm model.hh found in /home/liuyijiao/kenlm_install/include/kenlm/lm
> -- Found kenlm (include: /home/liuyijiao/kenlm_install/include, library: /home/liuyijiao/kenlm_install/lib/libkenlm.a;/home/liuyijiao/kenlm_install/lib/libkenlm_util.a;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)
> -- FL_BACKEND is not CUDA - forcing FL_LIBRARIES_USE_CUDA to OFF
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/liuyijiao/flashlight/bindings/python/build/temp.linux-x86_64-3.7
> [  2%] Performing update step for 'pybind11'
> [ 69%] Built target fl-libraries
> [ 71%] No configure step for 'pybind11'
> [ 73%] No build step for 'pybind11'
> [ 75%] No install step for 'pybind11'
> [ 77%] Completed 'pybind11'
> [ 83%] Built target pybind11
> [ 87%] Built target flashlight_lib_text_decoder
> [ 91%] Built target flashlight_lib_sequence_criterion
> [ 95%] Built target flashlight_lib_audio_feature
> [100%] Built target flashlight_lib_text_dictionary
> ------------debug /home/liuyijiao/flashlight/bindings/python/build/lib.linux-x86_64-3.7/flashlight/lib/text/dictionary.cpython-37m-x86_64-linux-gnu.so
> -- -rdynamic supported.
> -- Will build flashlight libraries.
> libraries criterions are not implemented for non-CUDA backends
> -- MKL_THREADING = OMP
> -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
> --   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
> --   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
> --   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
> --   Library gomp: -fopenmp
> --   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
> --   Library m: /usr/lib/x86_64-linux-gnu/libm.so
> --   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
> -- MKL library found
> -- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
> /home/liuyijiao/fftw/lib/cmake/fftw3
> -- FFTW found
> -- Looking for KenLM
> -- Using kenlm library found in /home/liuyijiao/kenlm_install/lib/libkenlm.a
> -- Using kenlm utils library found in /home/liuyijiao/kenlm_install/lib/libkenlm_util.a
> -- kenlm model.hh found in /home/liuyijiao/kenlm_install/include/kenlm/lm
> -- Found kenlm (include: /home/liuyijiao/kenlm_install/include, library: /home/liuyijiao/kenlm_install/lib/libkenlm.a;/home/liuyijiao/kenlm_install/lib/libkenlm_util.a;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)
> -- FL_BACKEND is not CUDA - forcing FL_LIBRARIES_USE_CUDA to OFF
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/liuyijiao/flashlight/bindings/python/build/temp.linux-x86_64-3.7
> [  2%] Performing update step for 'pybind11'
> [ 69%] Built target fl-libraries
> [ 71%] No configure step for 'pybind11'
> [ 73%] No build step for 'pybind11'
> [ 75%] No install step for 'pybind11'
> [ 77%] Completed 'pybind11'
> [ 83%] Built target pybind11
> [ 87%] Built target flashlight_lib_audio_feature
> [ 95%] Built target flashlight_lib_text_dictionary
> [ 95%] Built target flashlight_lib_text_decoder
> [100%] Built target flashlight_lib_sequence_criterion
> creating build/bdist.linux-x86_64
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/flashlight
> creating build/bdist.linux-x86_64/egg/flashlight/lib
> creating build/bdist.linux-x86_64/egg/flashlight/lib/text
> copying build/lib.linux-x86_64-3.7/flashlight/lib/text/decoder.py -> build/bdist.linux-x86_64/egg/flashlight/lib/text
> copying build/lib.linux-x86_64-3.7/flashlight/lib/text/flashlight_lib_text_decoder.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/flashlight/lib/text
> copying build/lib.linux-x86_64-3.7/flashlight/lib/text/flashlight_lib_text_dictionary.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/flashlight/lib/text
> copying build/lib.linux-x86_64-3.7/flashlight/lib/text/dictionary.py -> build/bdist.linux-x86_64/egg/flashlight/lib/text
> creating build/bdist.linux-x86_64/egg/flashlight/lib/sequence
> copying build/lib.linux-x86_64-3.7/flashlight/lib/sequence/flashlight_lib_sequence_criterion.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/flashlight/lib/sequence
> copying build/lib.linux-x86_64-3.7/flashlight/lib/sequence/criterion.py -> build/bdist.linux-x86_64/egg/flashlight/lib/sequence
> copying build/lib.linux-x86_64-3.7/flashlight/lib/sequence/criterion_torch.py -> build/bdist.linux-x86_64/egg/flashlight/lib/sequence
> creating build/bdist.linux-x86_64/egg/flashlight/lib/audio
> copying build/lib.linux-x86_64-3.7/flashlight/lib/audio/flashlight_lib_audio_feature.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/flashlight/lib/audio
> copying build/lib.linux-x86_64-3.7/flashlight/lib/audio/feature.py -> build/bdist.linux-x86_64/egg/flashlight/lib/audio
> copying build/lib.linux-x86_64-3.7/flashlight/lib/__init__.py -> build/bdist.linux-x86_64/egg/flashlight/lib
> copying build/lib.linux-x86_64-3.7/libfl-libraries.so -> build/bdist.linux-x86_64/egg
> copying build/lib.linux-x86_64-3.7/libfl-libraries.so.0.3 -> build/bdist.linux-x86_64/egg
> copying build/lib.linux-x86_64-3.7/libfl-libraries.so.0 -> build/bdist.linux-x86_64/egg
> byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/text/decoder.py to decoder.cpython-37.pyc
> byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/text/dictionary.py to dictionary.cpython-37.pyc
> byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/sequence/criterion.py to criterion.cpython-37.pyc
> byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/sequence/criterion_torch.py to criterion_torch.cpython-37.pyc
> byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/audio/feature.py to feature.cpython-37.pyc
> byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/__init__.py to __init__.cpython-37.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying flashlight.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying flashlight.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying flashlight.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying flashlight.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying flashlight.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
> creating dist
> creating 'dist/flashlight-1.0.0-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing flashlight-1.0.0-py3.7-linux-x86_64.egg
> creating /home/liuyijiao/torch_venv/lib/python3.7/site-packages/flashlight-1.0.0-py3.7-linux-x86_64.egg
> Extracting flashlight-1.0.0-py3.7-linux-x86_64.egg to /home/liuyijiao/torch_venv/lib/python3.7/site-packages
> Adding flashlight 1.0.0 to easy-install.pth file
> 
> Installed /home/liuyijiao/torch_venv/lib/python3.7/site-packages/flashlight-1.0.0-py3.7-linux-x86_64.egg
> Processing dependencies for flashlight==1.0.0
> Finished processing dependencies for flashlight==1.0.0

But when I import flashlight.lib.text.decoder, ImportError: /home/liuyijiao/arrayfire/lib64/libmkl_intel_lp64.so: undefined symbol: mkl_blas_mkl_cgemm_direct_jit happened

#### Additional Context
uname -a

> Linux  4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

python 3.7.3
using cpu backend

**Comment by tlikhomanenko** [comment]
Could you try to install without mkl `USE_MKL=0`? and try with it?

**Comment by akafen** [comment]
@tlikhomanenko 
I don't export mkl intel64 after arrayfire which causes the error.
This is correct:
`/opt/intel/mkl/lib/intel64_lin/:/opt/intel/mkl/lib/intel64:/opt/intel/mkl/lib/:/home/liuyijiao/gloo_install/lib/:/home/liuyijiao/arrayfire/lib64/`
This is wrong:
`/home/liuyijiao/gloo_install/lib/:/home/liuyijiao/arrayfire/lib64/:/opt/intel/mkl/lib/intel64_lin/:/opt/intel/mkl/lib/intel64:/opt/intel/mkl/lib/`

**Comment by tlikhomanenko** [comment]
Ok, did you finally solve the issue? If yes, please close the task, otherwise let me know what problem you still have.

**Comment by akafen** [comment]
@tlikhomanenko 
Yes, I solve the issue now.
