### ISSUE TITLE
 Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)

### ISSUE THREAD

**Issue by tensorfoo** [flashlight/flashlight#676]
Been stuck on trying to build the python bindings. I get this error and I don't know why it even wants MPI. I have used conda to install openmpi locally and am pretty sure the system has one somewhere as well. I've now also built my own copy of openmpi. No luck. Any work around appreciated.

**Comment by tensorfoo** [comment]
If there is a way to specify where openmpi lives or even better to remove this dependency on openmpi, i'd be very grateful to know.

**Comment by tensorfoo** [comment]
Sorry, I didn't keep a record (because there was nothing specific in it to help diagnose) and I don't think you would have found anything helpful from it either. From memory, after it tries the cmake command and returns an error (without saying anything specific about why it failed, just that it had). I gave up and tried again a few days later and was able to get cmake to build the flashlight project. But even then the setup.py install wasn't working and i had to comment out these lines: 
```
#        subprocess.check_call(
 #           ["cmake", source_dir] + cmake_args, cwd=self.build_temp, env=env
  #      )
   #     subprocess.check_call(
    #        ["cmake", "--build", "."] + build_args, cwd=self.build_temp
     #   )

```

After that I was finally able to build the bindings and use them. Took like 3 days of pulling my hair out. The main reason is probably having to use my school's Centos 7 machine without superuser access. But even then, in comparison installing and setting up say fairseq (including apex, torch etc) took a few hours max and I had no issues at all.

**Comment by jacobkahn** [comment]
@tensorfoo thanks for that input. Pending resources, we'll be removing OpenMPI as a hard dependency — it's on our todo list.
