### ISSUE TITLE
Limit use single thread/core for inferance ASR 

### ISSUE THREAD

**Issue by anjul1008** [flashlight/flashlight#724]
### Question
Hi,
I am able to build and run all module successfully for wav2wec2 training and decoding.

But when i use/import flashlight library it uses all the available threads/cores of the system, do we have any parameter to restrict threads/cores while using?
For example: by loading/using libs it uses all threads (not using GPU at inferance time)
    # from flashlight.lib.text.dictionary import create_word_dict, load_words
    # from flashlight.lib.sequence.criterion import CpuViterbiPath, get_data_ptr_as_bytes

any help will be appreciated.
Thank you

**Comment by tlikhomanenko** [comment]
For which particular function you need to limit number of threads?

**Comment by anjul1008** [comment]
Hi @tlikhomanenko 
Thanks for quick reply.
For now looking for below functions:
```
flashlight.lib.text.dictionary.*
flashlight.lib.sequence.criterion.*
flashlight.lib.text.decoder.*
```

This there any parameter that can be used for entire library?
Thank you

**Comment by anjul1008** [comment]
Thanks @joazoa @tlikhomanenko ,
This worked for me.
