### ISSUE TITLE
[Creating .srt and/or .vtt correctly formatted file(s)?]

### ISSUE THREAD

**Issue by dev2devportal** [flashlight/flashlight#740]
### Question
Is it possible to have wav2letter / flashlight-asr create .srt and/or .vtt formatted files? We have it working for human-readable transcripts. Would be really great if there were instructions on how to also create .srt and/or .vtt formatted files as well.

#### Additional Context
Greetings,

We are successfully using Vosk server with Jigasi for real-time closed captions.

We've been using wav2letter / flashlight-asr for offline human readable transcript from the Jibri recorded meeting successfully, because of the higher accuracy of wav2letter over Vosk.

Now we're trying to create both .srt and .vtt files from these Jitsi meetings, but having trouble finding information on how to do so with either tool. So we found about ten .vtt converters, but now trying to find .srt that we need to use for importing into Able Player.

This all seems like a lot of extra steps when we're already running wav2letter / Flashlight-ASR on the .wav file from the meeting recording for the human readable transcript. I had hoped it would be possible to use wav2letter / flashlight-asr to just create all of them at once, is this possible?

Is there a command/config switch we can enable for wav2letter / flashlight-asr to automatically save to all three formats:
1. Human readable transcript file (working)
2. And an .srt formatted file (need guidance if possible)
3. And a .vtt formatted file (need guidance if possible)
?

It would be so very nice if we could just handle all of this with one set of tools related to w2l / fasr.

Really appreciate suggestions on each part, and any specific config or command line options that would make this possible.

Thanks kindly!

**Comment by jacobkahn** [comment]
See my answer in https://github.com/flashlight/flashlight/discussions/737#discussioncomment-1390834.
