### ISSUE TITLE
Colab tutorial notebook errors out

### ISSUE THREAD

**Issue by vwrj** [flashlight/flashlight#764]
### Bug Description
Colab Notebook (`fl_asr_tutorial_inference_ctc`): https://colab.research.google.com/github/flashlight/flashlight/blob/master/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb

#### Reproduction Steps

I'm using the GPU runtime (CUDA backend) on the Colab. 

Running the second cell with the `cmake .. -DCMAKE_BUILD_...` command produces the following error:

```
env: MKLROOT=/opt/intel/mkl
env: ArrayFire_DIR=/opt/arrayfire/share/ArrayFire/cmake
env: DNNL_DIR=/opt/dnnl/dnnl_lnx_2.0.0_cpu_iomp/lib/cmake/dnnl
-- -rdynamic supported.
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_75,code=compute_75
CMake Error at cmake/InternalUtils.cmake:126 (message):
  FL_BUILD_CORE Required to build FL_BUILD_APP_ASR
Call Stack (most recent call first):
  flashlight/app/CMakeLists.txt:11 (fl_dependent_option)
  CMakeLists.txt:247 (include)
```

### Platform and Hardware
Colab with GPU. 

#### Additional Context
[Add any additional information here]

**Comment by pranavpawar3** [comment]
Hi @vwrj, I have been facing the same bug, it occurs on all the machines I tested (EC2 DL VM and local). Have you been able to resolve this bug?

**Comment by vwrj** [comment]
@pranavpawar3 using the previous flashlight release works -- thank you!
