### ISSUE TITLE
Make Error after successful CMake

### ISSUE THREAD

**Issue by avi-champ** [flashlight/flashlight#767]
make all is failing because CMake reported following errors mentioned in log below

Make Error:
/usr/bin/ld: cannot find -lcereal
/usr/bin/ld: cannot find -lArrayFire::afcpu
/usr/bin/ld: cannot find -lDNNL::dnnl
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/myProject.dir/build.make:86: myProject] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/myProject.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

CMake build result:
cmake ..   -DCMAKE_TOOLCHAIN_FILE=/root/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake   -DCMAKE_BUILD_TYPE=Release
CMake Warning (dev) at /root/Desktop/vcpkg/installed/x64-linux/share/flashlight/flashlightConfig.cmake:38 (if):
  if given arguments:

    "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  /root/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package)
  CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /root/Desktop/vcpkg/installed/x64-linux/share/flashlight/flashlightConfig.cmake:42 (if):
  if given arguments:

    "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  /root/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package)
  CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /root/Desktop/vcpkg/installed/x64-linux/share/flashlight/flashlightConfig.cmake:46 (if):
  if given arguments:

    "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  /root/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package)
  CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /root/Desktop/vcpkg/installed/x64-linux/share/flashlight/flashlightConfig.cmake:121 (if):
  if given arguments:

    "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  /root/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package)
  CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Error at /root/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "myProject" links to target "ArrayFire::afcpu" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:5 (add_executable)

CMake Error at /root/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "myProject" links to target "DNNL::dnnl" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:5 (add_executable)

CMake Warning (dev) at /root/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "myProject" links to some libraries for which the linker
  must search:

    cereal, ArrayFire::afcpu, -lpthread, dl, DNNL::dnnl, gloo

  and other libraries with known full path:

    /root/Desktop/vcpkg/installed/x64-linux/share/flashlight/../../lib/libflashlight.a

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
Call Stack (most recent call first):
  CMakeLists.txt:5 (add_executable)
This warning is for project developers.  Use -Wno-dev to suppress it.

I had installed FlashLight using following commands
./vcpkg/vcpkg install flashlight-cpu

Created CMake file as given in document:
cmake_minimum_required(VERSION 3.10)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(myProject project.cpp)

find_package(flashlight CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE flashlight::flashlight)

cd project && mkdir build && cd build
cmake .. \
  -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg clone]/scripts/buildsystems/vcpkg.cmake \
  -DCMAKE_BUILD_TYPE=Release
make -j$(nproc)

Platform 

RHEL 8.0, No Dedicated GPU, cmake version 3.11.4

**Comment by avi-champ** [comment]
Please suggest any workaround for the issue

**Comment by jacobkahn** [comment]
@avi-champ Can you install DNNL, ArrayFire CPU, and cereal with vcpkg and try again? Looks like they aren't installed.

**Comment by avi-champ** [comment]
Can you help how to get this done?

**Comment by jacobkahn** [comment]
```
./vcpkg install arrayfire[cpu] cereal onednn
```

**Comment by avi-champ** [comment]
Thanks. I have run this command and here are my results
Computing installation plan...
The following packages are already installed:
    arrayfire[core,cpu,unified]:x64-linux -> 3.8.0
    cereal[core]:x64-linux -> 1.3.0#1
    onednn[core]:x64-linux -> 2.4.3
Package arrayfire:x64-linux is already installed
Package cereal:x64-linux is already installed
Package onednn:x64-linux is already installed
Restored 0 packages from /root/.cache/vcpkg/archives in 2.934 us. Use --debug to see more details.
Total elapsed time: 6.685 s

The package arrayfire provides CMake targets:

    find_package(ArrayFire CONFIG REQUIRED)
    target_link_libraries(main PRIVATE ArrayFire::af ArrayFire::afcpu)

The package cereal provides CMake targets:

    find_package(cereal CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cereal)

The package onednn provides CMake targets:

    find_package(dnnl CONFIG REQUIRED)
    target_link_libraries(main PRIVATE DNNL::dnnl)

I have added the find_package and target_link_library to the CMakeLists.txt

cmake_minimum_required(VERSION 3.10)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)


add_executable(myProject project.cpp)

find_package(ArrayFire CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE ArrayFire::af ArrayFire::afcpu)

find_package(cereal CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE cereal)

find_package(dnnl CONFIG REQUIRED)
target_link_libraries(main PRIVATE DNNL::dnnl)

find_package(flashlight CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE flashlight::flashlight)

when i run cmake ..   -DCMAKE_TOOLCHAIN_FILE=[vcpkg loc]/scripts/buildsystems/vcpkg.cmake   
-DCMAKE_BUILD_TYPE=Release

i am getting following error
CMake Error at CMakeLists.txt:11 (find_package):
  Could not find a package configuration file provided by "cereal" with any
  of the following names:

    cerealConfig.cmake
    cereal-config.cmake

  Add the installation prefix of "cereal" to CMAKE_PREFIX_PATH or set
  "cereal_DIR" to a directory containing one of the above files.  If "cereal"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by avi-champ** [comment]
Thanks for the update. I have installed all 3 packages. Now I am getting error when I Make

[ 50%] Linking CXX executable myProject
/usr/bin/ld: warning: libmkl_core.so.1, needed by /root/Desktop/vcpkg/packages/arrayfire_x64-linux/lib/libaf.so.3.8.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libmkl_intel_lp64.so.1, needed by /root/Desktop/vcpkg/packages/arrayfire_x64-linux/lib/libaf.so.3.8.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libmkl_intel_thread.so.1, needed by /root/Desktop/vcpkg/packages/arrayfire_x64-linux/lib/libaf.so.3.8.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /root/Desktop/vcpkg/installed/x64-linux/lib/libdnnl.a(gemm_driver.cpp.o): undefined reference to symbol 'omp_in_parallel@@VERSION'
//opt/arrayfire/lib64/libiomp5.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/myProject.dir/build.make:93: myProject] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/myProject.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Can you please explain what could be the issue

**Comment by jacobkahn** [comment]
@avi-champ There should be a script as part of MKL/oneAPI that should set environment variables properly so that these libs can be found at compile time.

- [oneAPI setup](https://software.intel.com/content/www/us/en/develop/documentation/oneapi-programming-guide/top/oneapi-development-environment-setup.html)
- [`setvars.sh`](https://software.intel.com/content/www/us/en/develop/documentation/oneapi-programming-guide/top/oneapi-development-environment-setup/use-the-setvars-script-with-linux-or-macos.html)

**Comment by avi-champ** [comment]
@jacobkahn I have run that script but no success yet

source setvars.sh
 
:: initializing oneAPI environment ...
   bash: BASH_VERSION = 4.4.19(1)-release
:: advisor -- latest
:: ccl -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: intelpython -- latest
:: ipp -- latest
:: ippcp -- latest
:: ipp -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
:: vpl -- latest
:: vtune -- latest
:: oneAPI environment initialized ::

I am getting same error still

**Comment by avi-champ** [comment]
@jacobkahn When executed source setvars.sh from the directory of project (inside build) the following warnings went away
/usr/bin/ld: warning: libmkl_core.so.1, needed by /root/Desktop/vcpkg/packages/arrayfire_x64-linux/lib/libaf.so.3.8.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libmkl_intel_lp64.so.1, needed by /root/Desktop/vcpkg/packages/arrayfire_x64-linux/lib/libaf.so.3.8.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libmkl_intel_thread.so.1, needed by /root/Desktop/vcpkg/packages/arrayfire_x64-linux/lib/libaf.so.3.8.0, not found (try using -rpath or -rpath-link)

but the error still persist
usr/bin/ld: /root/Desktop/vcpkg/installed/x64-linux/lib/libdnnl.a(gemm_driver.cpp.o): undefined reference to symbol 'omp_in_parallel@@VERSION'
/opt/intel/oneapi/compiler/2021.4.0/linux/compiler/lib/intel64_lin/libiomp5.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/myProject.dir/build.make:93: myProject] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/myProject.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

when i Googled for DSO missing, i understood dynamic shared object missing and I added make -liomp5 but error is still present

2) Do I have to source the environment everytime?

**Comment by avi-champ** [comment]
Finally could solve the issue by updating the CMakeLists.txt

cmake_minimum_required(VERSION 3.10)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(MKL_DIR /opt/intel/oneapi/mkl)


add_executable(myProject project.cpp)

find_package(ArrayFire CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE ArrayFire::af ArrayFire::afcpu)

find_package(dnnl CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE DNNL::dnnl)

find_package(cereal CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE cereal)

find_package(Gloo CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE gloo)

target_include_directories(myProject PUBLIC "${MKL_DIR}/latest/include")
target_compile_definitions(myProject PUBLIC MKL_ILP64)
link_directories("${MKL_DIR}/latest/lib/intel64")
target_link_libraries(myProject PUBLIC mkl_intel_ilp64 mkl_intel_thread mkl_core iomp5 pthread m dl)


find_package(flashlight CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE flashlight::flashlight)

Thanks for help.
