### ISSUE TITLE
Can't install flashlight-cuda with vcpkg

### ISSUE THREAD

**Issue by All-Ki** [flashlight/flashlight#818]
### Bug Description
I have cuda and cudnn installed, though when i try to run vcpkg install flashlight-cuda it errors out

#### Reproduction Steps
./vcpkg install flashlight-cuda

### Platform and Hardware
Kali linux 2021.4

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_21:27:02_PDT_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0

#### Additional Context
./vcpkg install flashlight-cuda 
Computing installation plan...
The following packages will be built and installed:
  * arrayfire[core,cpu,cuda,unified]:x64-linux -> 3.8.0
  * cereal[core]:x64-linux -> 1.3.0#1
  * cub[core]:x64-linux -> 1.12.0
  * cuda[core]:x64-linux -> 10.1#8
  * cudnn[core]:x64-linux -> 7.6.5#4
  * egl-registry[core]:x64-linux -> 2021-11-23
    flashlight-cuda[core,fl]:x64-linux -> 0.3#2
  * fmt[core]:x64-linux -> 8.1.1
  * glad[core,loader]:x64-linux -> 0.1.34#3
  * intel-mkl[core]:x64-linux -> 2020.0.0#2
  * nccl[core]:x64-linux -> 2.4.6#2
  * opengl-registry[core]:x64-linux -> 2021-11-17
  * openmpi[core]:x64-linux -> 4.1.0#4
  * spdlog[core]:x64-linux -> 1.9.2
  * stb[core]:x64-linux -> 2020-09-14#1
  * vcpkg-cmake-config[core]:x64-linux -> 2021-12-28
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /root/.cache/vcpkg/archives in 15.02 us. Use --debug to see more details.
Starting package 1/16: cuda:x64-linux
Building package cuda[core]:x64-linux...
-- Executing NVCC-NOTFOUND --version resulted in error: 1
CMake Error at ports/cuda/vcpkg_find_cuda.cmake:67 (message):
  Could not find CUDA.  Before continuing, please download and install CUDA
  (v10.1.0 or higher) from:

      https://developer.nvidia.com/cuda-downloads

Call Stack (most recent call first):
  ports/cuda/portfile.cmake:9 (vcpkg_find_cuda)
  scripts/ports.cmake:142 (include)

Error: Building package cuda:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+cuda
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[cuda]+Build+error
including:
  package: cuda[core]:x64-linux -> 10.1#8
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 07e508359 2022-01-27 (2 hours ago)

Additionally, attach any relevant sections from the log files above.

**Comment by jacobkahn** [comment]
This looks like a problem with the CUDA vcpkg port finding your CUDA installation. I'd recommend opening an issue in the vcpkg repo.
