### ISSUE TITLE
vcpkg install - Error: openmpi[core] is only supported on '!(windows | uwp)' 

### ISSUE THREAD

**Issue by kommander** [flashlight/flashlight#826]
### Bug Description
Running `./vcpkg install flashlight-cuda`
Results in:
```
Error: openmpi[core] is only supported on '!(windows | uwp)'
```
This is the only output, nothing else.

#### Reproduction Steps
Just running  `./vcpkg install flashlight-cuda` on Win10

### Platform and Hardware
Win10, Nvidia RTX 3080 mobile, CUDA 11.6

EDIT: There is nothing really special about my setup, relatively fresh install. Just got vcpkg and ran install.

**Comment by kommander** [comment]
Saw vcpkg, assumed it would run on windows. I am not using windows voluntarily, believe you me. A note somewhere prominent on which platforms are supported would have saved me a day.

**Comment by jacobkahn** [comment]
Sorry you had trouble. Our [docs list](https://github.com/flashlight/flashlight#building-and-installing):

> At minimum, compilation requires:
> - A C++ compiler with good C++17 support (e.g. gcc/g++ >= 7)
> - [CMake](https://cmake.org/) — version 3.10 or later, and make
> - A Linux-based operating system.
