### ISSUE TITLE
Error compiling Python Bindings Because of DIR not found

### ISSUE THREAD

**Issue by cnlinxi** [flashlight/flashlight#830]
### Question
I want to [Evaluating a CTC model in wav2vec 2.0](https://github.com/pytorch/fairseq/blob/main/examples/wav2vec/README.md#evaluating-a-ctc-model), so I need to install [flashlight python bindings](https://github.com/facebookresearch/flashlight/tree/master/bindings/python). I follow [this](https://github.com/flashlight/flashlight/tree/main/bindings/python) instruction, but get many error likes Could NOT find GMock (missing: GMock_DIR) / Could NOT find GMock (missing: GMOCK_INCLUDE_DIRS). I install fftw3 / googletest from source, make them and add `bin` into bashrc.

#### Additional Context
I donot have root and cannot `yum install`, so some solutions above issues cannot take effect for me.

Thanks a lot.

**Comment by jacobkahn** [comment]
@cnlinxi — can you make sure that you're building GMock in addition to GTest? How are you installed gtest?

You can also run the build with the CMake option `FL_BUILD_TESTS=OFF` which will remove that dependency requirement.

**Comment by cnlinxi** [comment]
> @cnlinxi — can you make sure that you're building GMock in addition to GTest? How are you installed gtest?
> 
> You can also run the build with the CMake option `FL_BUILD_TESTS=OFF` which will remove that dependency requirement.

Thanks a lot. I fix it.
