### ISSUE TITLE
Cmake Issue Array Fire

### ISSUE THREAD

**Issue by Tom-Mirowski** [flashlight/flashlight#853]
Ubuntu 20.04
Cmake 3.16.3
GCC 9.4.0

Fresh system install, only trying to build Flashlight on it currently.

KENLM and MKL paths set.

Python binding install went well.

Using command 

`cmake .. -DFL_BACKEND=CPU -DCMAKE_BUILD_TYPE=Release -DFL_BUILD_TESTS=OFF -DFL_BUILD_EXAMPLES=OFF -DFL_BUILD_APP_ASR=ON`

Gets me to

-- ArrayFire found (include: /usr/include, library: )
CMake Error at flashlight/fl/tensor/backend/af/CMakeLists.txt:19 (message):
  ArrayFire CPU not found: cannot build CPU backend
Call Stack (most recent call first):
  flashlight/fl/tensor/CMakeLists.txt:6 (include)
  flashlight/fl/CMakeLists.txt:73 (include)
  CMakeLists.txt:217 (include)

Not sure where to go from here.

Arrayfire was installed via...

sudo apt-get update
sudo apt-get install libarrayfire-dev

EDIT :

Since then I have also tried downloading the file from ArrayFire directly, running their .sh setup script

ArrayFireSetup.sh --prefix=/opt
echo /opt/arrayfire/lib64 > /etc/ld.so.conf.d/arrayfire.conf
ldconfig

Reran the setup, same error.

And I still get the same error.

**Comment by jacobkahn** [comment]
If you can confirm that `libafcpu` is present on your system post-install? If it is, passing the `ArrayFire_DIR` option to CMake is required. I assume you've solved this based on your follow-up issues, but feel free to re-open if not.
