### ISSUE TITLE
No Build Folder after VCPKG?

### ISSUE THREAD

**Issue by Tom-Mirowski** [flashlight/flashlight#856]
I installed via vcpkg after installing MKL separately.  

This created a directory :

/home/username/vcpkg/buildtrees/flashlight-cpu/src/f7e2b796ad-7f3c690730.clean/

Inside here is a bindings, cmake, docs, flashlight and scripts folder.

However, I am looking for the *_ctc files that are usually in flashlight/build/bin/asr/*_ctc

Is there a reason these aren't built when doing ./vcpkg flashlight-cpu ?

To clarify, I am specifically looking for the following set of files at the end of my VCPKG Installation :

fl_asr_align   fl_asr_tutorial_finetune_ctc
fl_asr_decode  fl_asr_tutorial_inference_ctc
fl_asr_test    fl_asr_voice_activity_detection_ctc
fl_asr_train

**Comment by jacobkahn** [comment]
These will be found in the `[vcpkg install dir]/bin` rather than in a `build` directory.
