### ISSUE TITLE
Input values to Lexicon decoder.decode. Decoding causes segmentation fault (core dumped)

### ISSUE THREAD

**Issue by knightrogen** [flashlight/flashlight#882]
I have setuped flashlight and kenlm , also have exported the kenlm_root path before building the flashlight.

I am able to create lexicondecoder option object, kenlm object, lexicondecoder object. But as the values are passed to lexicondecoder.decode it shows segmentation fault core dumped. The error is showed after reading lm.arpa . 

Is this error coming from the type of input I am giving to decoder or is it some kenlm issue.

Currently I am passing input array.ctypes.data and T,N = shape of array.

**Comment by jacobkahn** [comment]
@knightrogen are you using the Python bindings or the C++ API?

Also, Flashlight Text has moved to https://github.com/flashlight/text — you might consider rebuilding using that codebase as well if you aren't dependent on Flashlight.

**Comment by kamirdin** [comment]
@jacobkahn  Hi, I encounter the same issue, I'm willing to try the new codebase, but a lot of code here do dependent on Flashlight:
https://github.com/facebookresearch/fairseq/blob/main/examples/speech_recognition/w2l_decoder.py
at line 136:
     self.lm = KenLM(args.kenlm_model, self.word_dict)
got a (core dumped) error, any  thought about it ？thank you

**Comment by jacobkahn** [comment]
Hi @kamirdin — do you have KenLM installed on your system? It's possible it's not found at runtime.

**Comment by kamirdin** [comment]
@jacobkahn thanks for your response! I do have installed KenLM and set  ‘export KENLM_ROOT=$mypath’ during python setup.py install . 
Do I need to set something intentionally at runtime?

**Comment by jacobkahn** [comment]
@kamirdin If this is happening with the fairseq KeNLM abstraction, I'd suggest opening an issue there. If you've installed KenLM and the bindings build has properly found them, you're doing everything right on the Flashlight side.
