### ISSUE TITLE
compilation error in RNN.cpp

### ISSUE THREAD

**Issue by felixt56** [flashlight/flashlight#894]
### Bug Description
RNN.cpp:87, 89, 126, ...
... error: no matching function for call to ‘fl::range::range(size_t)’ , or ‘fl::range::range(size_t&, size_t)’

#### Reproduction Steps
cmake . -B ./build -DFL_ARRAYFIRE_USE_CUDA=ON \  # or -DFL_ARRAYFIRE_USE_CPU
		   -DFL_BUILD_LIB_SEQUENCE=ON -DFL_BUILD_PKG_RUNTIME=ON \
		   -DFL_BUILD_LIB_AUDIO=ON -DFL_BUILD_PKG_SPEECH=ON -DFL_BUILD_APP_ASR=ON  #>> ../cmake-res.txt
cd build
make

### Platform and Hardware
[Please list your operating system, [GPU] hardware, compiler, and other details if relevant]
Ubuntu 22.04 Jammy Jellyfish (x86-64)
NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile]

#### Additional Context
[Add any additional information here]

**Comment by jacobkahn** [comment]
@felixt56 -- what's your version of gcc/clang? This sounds like a missing implicit include.

**Comment by felixt56** [comment]
I've cloned git once more on two machines and have built it with no errors.
