### ISSUE TITLE
flashlight.lib.text module is missing

### ISSUE THREAD

**Issue by kavnish** [flashlight/flashlight#911]
Sorry, I wasn't following the project in much detail. But one of my previous projects has a dependency on the beam-search decoder from the "flashlight.lib.text" module.

I was trying to build that project today and somehow the whole "flashlight.lib.text" module is missing.

Has there been any restructuring in the project wherein this module was moved somewhere else? if yes, where can I follow all the updates regarding this project?

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/35489661/176129006-7479a9b5-0af6-4f36-a882-82fbace4be8c.png">

**Comment by jacobkahn** [comment]
@kavnish — the flashlight text bindings were moved to Flashlight Text — https://github.com/flashlight/text. You can build those independently.

I'd freeze using Flashlight at v0.3.2 if you still want the bindings in their previous form. The `main` branch will move things around.

**Comment by kavnish** [comment]
thanks, @jacobkahn! where can I follow the development of this project? is there any such discord server/mail list?

**Comment by jacobkahn** [comment]
@kavnish Gitter chat's [here](https://gitter.im/flashlight-ml/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) which is best for support/questions.
