### ISSUE TITLE
ASR application build failed on undefined lm::ngram::LoadVirtual

### ISSUE THREAD

**Issue by zxpan** [flashlight/flashlight#912]
Someone might post the similar issue, but I did not find the solution or fix for that. Here is the issue

[100%] Built target fl_asr_test
/usr/bin/ld: ../../../../third-party/flashlight-text/src/flashlight-text-build/libflashlight-text.a(KenLM.cpp.o): in function `fl::lib::text::KenLM::KenLM(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, fl::lib::text::Dictionary const&)':
/workspace/flashlight/build/third-party/flashlight-text/src/flashlight-text/flashlight/lib/text/decoder/lm/KenLM.cpp:26: undefined reference to `lm::ngram::Config::Config()'
/usr/bin/ld: /workspace/flashlight/build/third-party/flashlight-text/src/flashlight-text/flashlight/lib/text/decoder/lm/KenLM.cpp:26: undefined reference to `lm::ngram::LoadVirtual(char const*, lm::ngram::Config const&, lm::ngram::ModelType)'
collect2: error: ld returned 1 exit status
make[2]: *** [flashlight/app/asr/tools/CMakeFiles/fl_asr_voice_activity_detection_ctc.dir/build.make:124: bin/asr/fl_asr_voice_activity_detection_ctc] Error 1
make[1]: *** [CMakeFiles/Makefile2:1276: flashlight/app/asr/tools/CMakeFiles/fl_asr_voice_activity_detection_ctc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: third-party/flashlight-text/src/flashlight-text-build/libflashlight-text.a(KenLM.cpp.o): in function `fl::lib::text::KenLM::KenLM(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, fl::lib::text::Dictionary const&)':
/workspace/flashlight/build/third-party/flashlight-text/src/flashlight-text/flashlight/lib/text/decoder/lm/KenLM.cpp:26: undefined reference to `lm::ngram::Config::Config()'
/usr/bin/ld: /workspace/flashlight/build/third-party/flashlight-text/src/flashlight-text/flashlight/lib/text/decoder/lm/KenLM.cpp:26: undefined reference to `lm::ngram::LoadVirtual(char const*, lm::ngram::Config const&, lm::ngram::ModelType)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fl_asr_decode.dir/build.make:124: bin/asr/fl_asr_decode] Error 1
make[1]: *** [CMakeFiles/Makefile2:175: CMakeFiles/fl_asr_decode.dir/all] Error 2
/usr/bin/ld: third-party/flashlight-text/src/flashlight-text-build/libflashlight-text.a(KenLM.cpp.o): in function `fl::lib::text::KenLM::KenLM(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, fl::lib::text::Dictionary const&)':
/workspace/flashlight/build/third-party/flashlight-text/src/flashlight-text/flashlight/lib/text/decoder/lm/KenLM.cpp:26: undefined reference to `lm::ngram::Config::Config()'
/usr/bin/ld: /workspace/flashlight/build/third-party/flashlight-text/src/flashlight-text/flashlight/lib/text/decoder/lm/KenLM.cpp:26: undefined reference to `lm::ngram::LoadVirtual(char const*, lm::ngram::Config const&, lm::ngram::ModelType)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fl_asr_train.dir/build.make:124: bin/asr/fl_asr_train] Error 1
make[1]: *** [CMakeFiles/Makefile2:477: CMakeFiles/fl_asr_train.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

Apparently this is due to the dependency issue to link kenlm library,  not sure how to fix it.

**Comment by zxpan** [comment]
it works only if building flashlight-text before building asr application
1) git clone https://github.com/flashlight/text;
cd text && mkdir build && cd build && cmake -DFL_TEXT_USE_KENLM=ON ..
2) then build asr application

**Comment by jacobkahn** [comment]
@zxpan can you post your original build command? We're still resolving some potential issues with KenLM symbols.

**Comment by zxpan** [comment]
my original build command is (after clone and mkdir build directory), based on latest code repo
`cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/opt/flashlight -DFL_BACKEND=CUDA -DFL_BUILD_LIB_AUDIO=ON -DFL_BUILD_LIB_SEQUENCE=ON -DFL_BUILD_PKG_RUNTIME=ON -DFL_BUILD_PKG_SPEECH=ON -DFL_BUILD_APP_ASR=ON -DFL_BUILD_APP_IMGCLASS=OFF -DFL_BUILD_APP_LM=OFF -DFL_BUILD_TESTS=OFF -DFL_BUILD_EXAMPLES=OFF -DFL_BUILD_ARRAYFIRE=ON -DFL_USE_TENSOR_STUB=OFF -DFL_ARRAYFIRE_USE_CUDA=ON -DFL_TEXT_USE_KENLM=ON`

**Comment by jacobkahn** [comment]
@zxpan — reproduced the issue. Working on a fix.
