### ISSUE TITLE
Load pre-trained rasr model failed

### ISSUE THREAD

**Issue by zxpan** [flashlight/flashlight#916]
### Bug Description
I built the latest flashlight asr application with CUDA GeForce RTX 3090, I got the following error when I run fl_asr_decode  with loading rasr pretrained model `am_transformer_ctc_stride3_letters_300Mparams.bin`

```
bin/asr/fl_asr_decode --flagfile /workspace/data/decode.cfg 
CachingMemoryManager recyclingSizeLimit_=18446744073709551615 (16777216.00 TiB) splitSizeLimit_=18446744073709551615 (16777216.00 TiB)



E0629 21:10:56.165144 19168 Serializer.h:83 Error while loading ""/workspace/model/am_transformer_ctc_stride3_letters_300Mparams.bin"": Failed to read 34359738368 bytes from input stream! Read 2147265725
```

any idea what's wrong with that?   The error more or less related to serialize the network as <fl::Module>

**Comment by zxpan** [comment]
Are there any code changes for fl::Module which cause incompatible issues for loading the model which are saved in old code?

**Comment by jacobkahn** [comment]
@zxpan — unfortunately, there are significant breaking changes currently on master which may cause those models not to load. If you can check out `v0.3.2`, things should hopefully work.

We hope to add serialization support for old models in the next minor release, but for now, using the [0.3 branch](https://github.com/flashlight/flashlight/tree/0.3) is best.

**Comment by zxpan** [comment]
Thanks for confirming this.
