### ISSUE TITLE
ModuleNotFoundError: No module named 'flashlight.lib.text'

### ISSUE THREAD

**Issue by SidM1811** [flashlight/flashlight#946]
I'm trying to run single file inference from [https://github.com/Open-Speech-EkStep/vakyansh-wav2vec2-experimentation](https://github.com/Open-Speech-EkStep/vakyansh-wav2vec2-experimentation)  I'm getting issues with an import statement that reads 'import flashlight.lib.text'. I have followed the instructions on the link and have also tried the same with python 3.8. There seems to be an issue with the text file in /bindings/python/flashlight/lib. This has been removed in the commit ee2f9be5de and has been 'abstracted away'. Any pointers on how to fix this would be great

**Comment by jacobkahn** [comment]
@SidM1811 — you have two options:
1. Check out Flashlight [`v0.3.2`](https://github.com/flashlight/flashlight/tree/v0.3.2) (`git checkout v0.3.2`) and install the bindings
2. Install the bindings from [Flashlight Text](https://github.com/flashlight/text).

I've created a PR to update that repo's readme as well — https://github.com/Open-Speech-EkStep/vakyansh-wav2vec2-experimentation/pull/31; you can also follow instructions.

Let me know if you're still having any issues.
