### ISSUE TITLE
error while loading Audio Model

### ISSUE THREAD

**Issue by felixt56** [flashlight/flashlight#983]
### Bug Description
[A clear, concise description of the bug]
error while loading  Audio Model

#### Reproduction Steps
[Steps to reproduce. Please include, if needed for your issue:
./build/bin/asr/fl_asr_tutorial_inference_ctc \
> --am_path=./models/am_conformer_ctc_stride3_letters_25Mparams.bin \
> --tokens_path=./models/tokens.txt \
> --lexicon_path=./models/lexicon.txt \
> --lm_path=./models/lm_common_crawl_small_4gram_prun0-6-15_200kvocab.bin \
> --audio_list=./models/audio_list.txt
E0815 10:24:01.434564 88480 Serializer.h:83 Error while loading ""./models/am_conformer_ctc_stride3_letters_25Mparams.bin"": std::bad_alloc

E0815 10:24:02.439431 88480 Serializer.h:83 Error while loading ""./models/am_conformer_ctc_stride3_letters_25Mparams.bin"": std::bad_alloc

E0815 10:24:04.444816 88480 Serializer.h:83 Error while loading ""./models/am_conformer_ctc_stride3_letters_25Mparams.bin"": std::bad_alloc

E0815 10:24:08.447935 88480 Serializer.h:83 Error while loading ""./models/am_conformer_ctc_stride3_letters_25Mparams.bin"": std::bad_alloc

E0815 10:24:16.453296 88480 Serializer.h:83 Error while loading ""./models/am_conformer_ctc_stride3_letters_25Mparams.bin"": std::bad_alloc

E0815 10:24:32.457677 88480 Serializer.h:83 Error while loading ""./models/am_conformer_ctc_stride3_letters_25Mparams.bin"": std::bad_alloc

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1660548272 (unix time) try "date -d @1660548272" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e80000ffb5) received by PID 65461 (TID 0x7f2b07099000) from PID 65461; stack trace: ***
    @     0x7f2b99b67046 (unknown)
    @     0x7f2b0b657520 (unknown)
    @     0x7f2b0b6aba7c pthread_kill
    @     0x7f2b0b657476 raise
    @     0x7f2b0b63d7f3 abort
    @     0x7f2b28316485 __gnu_cxx::__verbose_terminate_handler()
    @     0x7f2b28281216 __cxxabiv1::__terminate()
    @     0x7f2b28281261 std::terminate()
    @     0x7f2b28274c86 __cxa_rethrow
    @     0x55a845200f55 fl::retryWithBackoff<>()
    @     0x55a8451fd515 fl::pkg::runtime::Serializer::load<>()
    @     0x55a8451ef960 loadModel()
    @     0x55a8451f03a1 main
    @     0x7f2b0b63ed90 (unknown)
    @     0x7f2b0b63ee40 __libc_start_main
    @     0x55a8451eee25 _start
    @                0x0 (unknown)
Aborted (core dumped)

### Platform and Hardware
[Please list your operating system, [GPU] hardware, compiler, and other details if relevant]
Ubuntu 22.04 Jammy Jellyfish (x86-64)
NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile]
[nvidia-smi-out.txt](https://github.com/flashlight/flashlight/files/9335764/nvidia-smi-out.txt)

#### Additional Context
[Add any additional information here]

**Comment by jacobkahn** [comment]
We don't have yet compatibility with old models in master -- checkout `v0.3.2` and build there to load this model.
